### ISSUE TITLE
[Feature] Support for search templates / stored scripts

### ISSUE THREAD

**Issue by fludo** [elastic/terraform-provider-elasticstack#107]
We have many search template we deploy per-stack using the API/Dev-tools. This is actually errror-prone and we would like to include it in our Terraform scripts so we can manage it efficiently.

**Available APIs**
Create&Update script: https://www.elastic.co/guide/en/elasticsearch/reference/current/create-stored-script-api.html
Check currently deployed scripts: https://www.elastic.co/guide/en/elasticsearch/reference/current/get-stored-script-api.html

**Solution**
Provide support to create/update/delete scripts & search template

**Describe alternatives you've considered**
Using API / Dev console with query stored in standalone text file.

**Comment by fludo** [comment]
Any news on this feature request ?

**Comment by tobio** [comment]
This has been released with [0.5.0](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.5.0)
