### ISSUE TITLE
[Bug] Not able to set array as value in index settings

### ISSUE THREAD

**Issue by bruno-s-coelho** [elastic/terraform-provider-elasticstack#108]
**Describe the bug**
We need to create an index with the following settings:
```
"settings": {
        "index": {
            "number_of_shards": "3",
            "analysis": {
                "normalizer": {
                    "keyword_normalizer": {
                        "type": "custom",
                        "char_filter": [],
                        "filter": [
                            "lowercase",
                            "asciifolding"
                        ]
                    }
                }
            }
        }
    },
```

When we are defining settings, the provider is just accepting string values.

**To Reproduce**
The configuration used was the following one:
```
resource "elasticstack_elasticsearch_index" "my_index" {
  name = "my-index"

  alias {
    name = "my_alias_1"
  }

  alias {
    name = "my_alias_2"
    filter = jsonencode({
      term = { "user.id" = "developer" }
    })
  }

  mappings = jsonencode({
    properties = {
      field1 = { type = "keyword" }
    }
  })

  settings {
    setting {
      name  = "index.number_of_shards"
      value = "1"
    }
    setting {
      name  = "index.number_of_replicas"
      value = "2"
    }
    setting {
      name  = "index.analysis.normalizer.keyword_normalizer.filter"
      value = "['lowercase', 'asciifolding']"
    }
  }
}
```

When terraform apply is executed, the output is:

Failed with:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Custom
Analyzer [keyword_normalizer] failed to find filter under name
[[\"lowercase\"]"}],"type":"illegal_argument_exception","reason":"Custom
Analyzer [keyword_normalizer] failed to find filter under name
[[\"lowercase\"]"},"status":400}

**Expected behavior**
We were expecting to have a new index with the alias and the settings as well created.

**Debug output**
```
 Error: Unable to create index: my-index
│ 
│   with elasticstack_elasticsearch_index.my_index,
│   on indices.tf line 1, in resource "elasticstack_elasticsearch_index" "my_index":
│    1: resource "elasticstack_elasticsearch_index" "my_index" {
│ 
│ Failed with: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Custom Analyzer [keyword_normalizer] failed to find
│ filter under name [['lowercase']"}],"type":"illegal_argument_exception","reason":"Custom Analyzer [keyword_normalizer] failed to find
│ filter under name [['lowercase']"},"status":400}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/97046871/167121712-e4634c0d-5c79-43d1-a55a-ae3c189744d7.png)

**Versions (please complete the following information):**
- OS: linux
- Terraform Version 1.1.9
- Provider version 0.3.3
- Elasticsearch Version 7.9.1

**Comment by bruno-s-coelho** [comment]
Can I get some feedback here?
Thanks

**Comment by tobio** [comment]
Fixed as part of https://github.com/elastic/terraform-provider-elasticstack/pull/137
