### ISSUE TITLE
[Bug] elasticsearch_index_lifecycle - terraform plan bug

### ISSUE THREAD

**Issue by greibrokka** [elastic/terraform-provider-elasticstack#113]
**Describe the bug**
Terraform plan throws error when referring to a ILM which contains a rollover with size in g as gb had been used

**To Reproduce**

1. Adding index_lifecycles.tf
2. Terraform plan or apply doesn't throw any error
3. When referring to this ILM in a component template - component_templates.tf
4. Terraform plan throws this error, even though apply is successful.

**Code and terraform output**
```
#filename: index_lifecycles.tf
resource "elasticstack_elasticsearch_index_lifecycle" "my_test_ilm" {
  name = "my_test_ilm_policy"

  hot {
    set_priority {
      priority = 100
    }
    rollover {
      max_age  = "7d"
      max_size = "30g"

    }
  }

  warm {
    min_age = "7d"
    set_priority {
      priority = 50
    }
    readonly {}
    allocate {
      exclude = jsonencode({
        box_type = "hot"
      })
      number_of_replicas = 1
    }
    forcemerge {
      max_num_segments = 1
    }
  }

  cold {
    min_age = "14d"
    readonly {}
  }

  delete {
    min_age = "30d"
    delete {}
  }
}

#filename: component_templates.tf
resource "elasticstack_elasticsearch_component_template" "component_template_test" {
  name = "component_template_test"

  template {

    settings = jsonencode({
      "lifecycle.name" = elasticstack_elasticsearch_index_lifecycle.my_test_ilm.name
    })
  }
}

# terraform error:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create
~   update in-place

Terraform will perform the following actions:

  # elasticstack_elasticsearch_component_template.component_template_test will be created
+   resource "elasticstack_elasticsearch_component_template" "component_template_test" {
+       id   = (known after apply)
+       name = "component_template_test"

+       template {
+           settings = jsonencode(
                {
+                   lifecycle.name = "my_test_ilm_policy"
                }
            )
        }
    }

  # elasticstack_elasticsearch_index_lifecycle.my_test_ilm will be updated in-place
~   resource "elasticstack_elasticsearch_index_lifecycle" "my_test_ilm" {
        id            = "Y1jbCnIYTUCT9lpJFSgpnQ/my_test_ilm_policy"
        name          = "my_test_ilm_policy"
        # (1 unchanged attribute hidden)



~       hot {
            # (1 unchanged attribute hidden)

~           rollover {
~               max_size = "30gb" -> "30g"
                # (2 unchanged attributes hidden)
            }

            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
```

**Expected behavior**
Terraform apply should not throw any error as the API documentation shows example of both G and GB being used
https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-rollover.html

**Screenshots**
![image](https://user-images.githubusercontent.com/84507859/171193197-c9ae0258-3f92-434f-a0d7-d760eb60367e.png)

**Versions (please complete the following information):**
 - OS: ES on Azure
 - Terraform Version 3.8.0
 - Provider version 0.3.3
 - Elasticsearch Version 8.2.2 (had same issue with 8.1.1 and 8.2.1)
 
**Additional context**
The terraform example/documentation should probably also be update with an example of the correct usage of rollover max_size.

**Comment by RobsonSutton** [comment]
@greibrokka -

If you take a look here (https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#byte-units) at the byte size units for the API conventions, it is documented as only supporting `gb` for gigabytes and not `g`. 

This is referenced as the unit type used for the `max_size` attribute (https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-rollover.html). 

The use of `g` is just a typo in that last screenshot within the elastic doc for ILM rollover.

I've raised a PR against elastic/elasticsearch to resolve the typo in the docs so that should clear up this issue from cropping up again with any other users.

**Comment by greibrokka** [comment]
@RobsonSutton 
Thank you for the feedback.
