### ISSUE TITLE
[Bug] Import elasticstack_elasticsearch_security_user resources fails with connection refused

### ISSUE THREAD

**Issue by PlugaruT** [elastic/terraform-provider-elasticstack#114]
**Describe the bug**

Provider fails to use the correct connection settings defined in TF. We have configured the connection configuration just like in the tutorial in [here](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/guides/elasticstack-and-cloud). When running `terraform plan` or `terraform apply` everything works as expected.
The problem is when trying to import an existing used into TF state. Doing it like this:
```
terraform import module.elastic_us_east4_a5a0.elasticstack_elasticsearch_security_user.user\[\"email@redacted\"\] 9c2f09e0a80bcfa61343fbadedb39b57/email@redacted
```
Fails with connection refused:
```
Error: dial tcp [::1]:9200: connect: connection refused
```

If hardcoding the correct URL, username and password at the provider definition, then we are able to import the existing users. Switching back to the way credentials are provided by the output of `ec_deployment` we can't even do `terraform plan` as it fails with the same error.

**To Reproduce**
1. Define an `ec_deployment` and run `terraform apply`
2. Go to the elastic.co UI and create a user via Kibana 
3. Define the `elasticstack_elasticsearch_security_user` resources and try to import the already existing user.

**Expected behavior**
Importing should work as expected.

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations.
```
2022-06-01T18:56:58.114+0300 [TRACE] vertex "module.elastic_us_east4_a5a0.elasticstack_elasticsearch_security_user.user (expand)": dynamic subgraph encountered errors: dial tcp [::1]:9200: connect: connection refused,dial tcp [::1]:9200: connect: connection refused
2022-06-01T18:56:58.114+0300 [ERROR] vertex "module.elastic_us_east4_a5a0.elasticstack_elasticsearch_security_user.user (expand)" error: dial tcp [::1]:9200: connect: connection refused
2022-06-01T18:56:58.114+0300 [ERROR] vertex "module.elastic_us_east4_a5a0.elasticstack_elasticsearch_security_user.user (expand)" error: dial tcp [::1]:9200: connect: connection refused
2022-06-01T18:56:58.114+0300 [TRACE] vertex "module.elastic_us_east4_a5a0.elasticstack_elasticsearch_security_user.user (expand)": visit complete, with errors
```

**Screenshots**

**Versions (please complete the following information):**
 - OS: MacOS
 - Terraform Version [e.g. 1.0.0]: 1.1.3
 - Provider version [e.g. v0.1.0]: 0.3.3
 - Elasticsearch Version [e.g. 7.16.0]: 8.1.3

**Additional context**

**Comment by tobio** [comment]
@PlugaruT using the `elasticsearch_connection` should likely be a last resort, I'm updating the Cloud guide to instead configure the Elasticsearch connection directly on the provider. 

During an import, the defined resource configuration is not made available to the provider, in this case it means that no Elasticsearch connection information is available. There's two solutions here:

1. Move the connection configuration to the `elasticstack` provider configuration, e.g:
```hcl 

provider "elasticstack" {
  elasticsearch {
    endpoints = ["${ec_deployment.cluster.elasticsearch[0].https_endpoint}"]
    username  = ec_deployment.cluster.elasticsearch_username
    password  = ec_deployment.cluster.elasticsearch_password
  }
}
```

2. Manually configure the ES connection information through environment variables for the import:

```
ELASTICSEARCH_ENDPOINTS=https://cloud-deployment-url ELASTICSEARCH_USERNAME=elastic ELASTICSEARCH_PASSWORD=foo terraform import ...
```
