### ISSUE TITLE
[Feature] Need support for Logstash Pipeline Terraform Resource in Elastic Cloud

### ISSUE THREAD

**Issue by raswinraaj** [elastic/terraform-provider-elasticstack#115]
**Is your feature request related to a problem? Please describe.**
Currently, the Elasticstack provider has support only for Ingest Pipelines. Need a similar support for Logstash pipelines

**Describe the resource you would like to have implemented.**
Logstash Pipeline

**Describe the solution you'd like**
Need a terraform resource which will help in creating Logstash Pipeline

**Describe alternatives you've considered**
As of now, i am using API call as described in https://www.elastic.co/guide/en/kibana/master/logstash-configuration-management-api-create.html

**Additional context**

**Comment by tobio** [comment]
This has been released with [0.5.0](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.5.0)
