### ISSUE TITLE
[Bug] unable to create index with analyzer and normalizer in setting sections

### ISSUE THREAD

**Issue by sangeethdba** [elastic/terraform-provider-elasticstack#119]
**Describe the bug**
unable to create index with analyzer and normalizer in setting sections

**Expected behavior**
need an example of index creation which has custom normalizer and analyzer define

**Versions (please complete the following information):**
 - OS: [e.g. Linux]
 - Terraform Version [e.g. 1.0.0]
 - Provider version [e.g. v0.1.0]
 - Elasticsearch Version [e.g. 7.16.0]

**Additional context**

**Comment by sangeethdba** [comment]
settings {
    setting {
      name  = "index.number_of_shards"
      value = "1"
    }
    setting {
      name  = "index.number_of_replicas"
      value = "1"
    }
    setting {
      name  = "index.search.idle.after"
      value = "20s"
    }
     analysis {
normalizer {
   lowercase_normalizer = {
      "type" = "custom",
      "filter" = [
        "lowercase", "asciifolding"
      ]
    }

**Comment by sangeethdba** [comment]
╷
│ Error: Unsupported block type
│
│   on test_1.tf line 712, in resource "elasticstack_elasticsearch_index" "idx_qa_7":
│  712:      analysis {
│
│ Blocks of type "analysis" are not expected here.

**Comment by tobio** [comment]
Fixed as part of https://github.com/elastic/terraform-provider-elasticstack/pull/137
