### ISSUE TITLE
[Bug] Issues with passing down the elasticstack provider to a child module.

### ISSUE THREAD

**Issue by RyanHealey1307** [elastic/terraform-provider-elasticstack#135]
**Describe the bug**
I am having issues with passing down the elasticstack provider to a child module.

I'm using the elasticstack provider in a custom Terraform module - which creates some resources, like datastreams, index templates, roles, users, etc.
I have a pipeline which deploys infrastructure for Logstash via Terraform - part of which is calling the above module.

I'm trying to pass down the provider config at the root of the module - as recommended by HashiCorp (https://www.terraform.io/language/modules/develop/providers#provider-aliases-within-modules). But I am getting the following error message:
```
Error: Provider type mismatch

on main.tf line 59, in module "logstash":
59:     elasticstack = elasticstack

The local name "elasticstack" in the root module represents provider
"hashicorp/elasticstack", but "elasticstack" in module.logstash represents
"elastic/elasticstack".

Each provider has its own distinct configuration schema and provider types,
so this module's "elasticstack" can be assigned only a configuration for
elastic/elasticstack, which is not required by module.logstash.
```

The repo is as follows:

![image](https://user-images.githubusercontent.com/90855375/184350667-b5c27529-3a9a-4cf6-943e-aad62bae8aea.png)

Providers in infra directory (providers.tf (1)):
```
terraform {
  required_providers {
    ### other provider
    elasticstack = {
      source = "elastic/elasticstack"
      configuration_aliases = [elasticstack]
    }
  }
}
```

Module call and provider config in env directory (main.tf):
```
module "pe_tf_module_elastic_tribe_config" {
  providers = {
    aws          = aws
    elasticstack = elasticstack
  }
  source         = "./modules/elastic_stack_config"
```

Providers in module (providers.tf (2)):
```
terraform {
  required_providers {
    ### other provider
    elasticstack = {
      source = "elastic/elasticstack"
      configuration_aliases = [elasticstack]
    }
  }
}
```

Providers in env directory (providers.tf (3)):
```
provider "elasticstack" {
  elasticsearch {
    endpoints = local.elastic_provider_config.endpoints
    username  = local.elastic_provider_config.username
    password  = local.elastic_provider_config.password
  }
}
```

Module call and provider config in env directory (main.tf):
```
module "logstash" {
  source = "../../../"
  providers = {
    aws  = aws
    aws.management = aws.management
    elasticstack = elasticstack
  }
```

**Expected behavior**
I use the same configuration_alias set up for the AWS provider and set the config when calling the module (defined at /infra) at /env - mian.tf - this works - I would expect the elasticstack provider to work the same. 

**Versions:**
 - Terraform Version 1.2.4
 - Provider version 0.3.3
 - Elasticsearch Version 8.2.3

Please can you advise how to resolve the issue / if this is a big with the provider. As far as I'm aware, my provider config is correct. As stated earlier, this is the exact method we use for the AWS provider which works.

**Comment by conlon-cognite** [comment]
@RyanHealey1307 I know you made this quite a while ago, but did you reach a solution to this?
