### ISSUE TITLE
v0.4.0 not released in the official terraform providers

### ISSUE THREAD

**Issue by othmane399** [elastic/terraform-provider-elasticstack#156]
Hello,

v0.4.0 is not released yet in the terraform providers official https://registry.terraform.io/providers/elastic/elasticstack/latest

is something missing or just need to wait couple of days ?

**Comment by tobio** [comment]
Thanks for the issue, we've been tracking down some permissions issues. 0.4.0 is available in the registry now:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/444668/196304159-e4163489-f0b3-4831-a5e4-47be1b3819f2.png">
