### ISSUE TITLE
Put link to terraform registry in About section

### ISSUE THREAD

**Issue by k-yomo** [elastic/terraform-provider-elasticstack#164]
It would be great if we could put the below link in about section like [the other providers do](https://github.com/hashicorp/terraform-provider-google) to be able to quickly jump to the doc.
https://registry.terraform.io/providers/elastic/elasticstack/latest/docs

**Comment by tobio** [comment]
Yea, good idea. Done.

**Comment by k-yomo** [comment]
@tobio 
Thank you!
