### ISSUE TITLE
[Feature] Make index resource safer to manage

### ISSUE THREAD

**Issue by k-yomo** [elastic/terraform-provider-elasticstack#165]
We may want to have `deletion_protection` in `index` resource like cloud SQL or the other important resources have to prevent unintended deletion.
The `deletion_protection` should be `true` by default and need to be updated it to `false` when we truly want to delete the index. With this, we will have a safer way to manage indices for production use cases.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance

**Comment by tobio** [comment]
@Kushmaro FYI.
