### ISSUE TITLE
[Feature] Add basic PR checks as Github actions

### ISSUE THREAD

**Issue by tobio** [elastic/terraform-provider-elasticstack#168]
Lint is run as part of the current acceptance test task, however this isn't run automatically for community sourced PR's which unnecessarily lengthens the feedback cycle for those PR's. Basic CI checks should be automatically triggered for all PRs via GH actions, they should include:

* Lint + Compilation
* Unit tests
* That there are no uncommitted docs changes

**Comment by k-yomo** [comment]
I would love to have CI on github actions to let community contributors to work easily on the project.
Could we also move acceptance tests to Github actions?
