### ISSUE TITLE
[Feature] elasticstack_elasticsearch_security_role_mapping

### ISSUE THREAD

**Issue by chr-b** [elastic/terraform-provider-elasticstack#192]
**Is your feature request related to a problem? Please describe.**
The current provider already supports the `elasticstack_elasticsearch_security_role` resource. However, creating a security role mapping is currently not available. 
This is limiting the usability of the security role resource itself, because I can't map it with Terraform.

**Describe the resource you would like to have implemented.**
The possibility to create [a role mapping](https://www.elastic.co/guide/en/elasticsearch/reference/8.5/role-mapping-resources.html#mapping-roles-rule-field) from Terraform.

**Describe the solution you'd like**
An `elasticstack_elasticsearch_security_role_mapping` resource that allows me to create a role mapping with:
* Mapping name
* A list of roles that can be assigned to the mapping 
* And mapping rules

**Describe alternatives you've considered**
Corresponding API calls:
* Create or update role mappings API: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role-mapping.html
* Delete role mappings API: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-delete-role-mapping.html#security-api-delete-role-mapping

**Additional context**
none

**Comment by k-yomo** [comment]
@chr-b 
security role mapping is added to the latest version v0.4.0!
https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_security_role_mapping

I missed to set subcategory when I added the resource, so now it's not under security category...! (It'll be fixed in the next release)

**Comment by chr-b** [comment]
Oh, sorry, totally missed that.
Thanks for the hint :)
