### ISSUE TITLE
[Feature] ECK Resources

### ISSUE THREAD

**Issue by BenB196** [elastic/terraform-provider-elasticstack#237]
**Is your feature request related to a problem? Please describe.**
I would like to be able to easily define various ECK resources via a Terraform module

**Describe the resource you would like to have implemented.**
ECK deployable resources (Elasticsearch, Kibana, Beats, Elastic Agent, etc...)

**Describe the solution you'd like**
I'd like the Terraform provider to have a well defined way of deploying ECK resources to Kubernetes clusters, then being able to manage them with the other Terraform provider resources.

**Describe alternatives you've considered**
I could use the [`kubernetes_manifest`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest), but this method is less user friendly, as the user has to know what they're doing. And there have been a number of issues/oddities reported when using this method:

- https://discuss.elastic.co/t/upgrade-es-version-managed-by-eck-on-terraform-all-pods-terminated/320897?u=benb196
- https://discuss.hashicorp.com/t/problem-with-preventing-deletion-of-elastic-volumeclaimtemplate-created-by-terraform/43983?u=benb196

**Comment by Kushmaro** [comment]
Hi @BenB196, ECK is outside the scope for this provider.
