### ISSUE TITLE
[Bug] Cannot delete ec_deployment and resources used internally in the deployment such as user at once

### ISSUE THREAD

**Issue by takashi-yokoyama-visasq** [elastic/terraform-provider-elasticstack#249]
I cannot delete all resources at once after I created the resources according to the example in the below link.
https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/guides/elasticstack-and-cloud

## To Reproduce

1. TF configuration 

```
terraform {
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.5.0"
    }
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "0.5.0"
    }
  }
  required_version = "1.3.7"
}

provider "ec" {
  apikey = "<my api key>"
}

resource "ec_deployment" "cluster" {
  region                 = "gcp-us-central1"
  name                   = "my-deployment"
  version                = data.ec_stack.latest.version
  deployment_template_id = "gcp-storage-optimized"

  elasticsearch {}
}

data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "gcp-us-central1"
}

provider "elasticstack" {
  elasticsearch {
    endpoints = ["${ec_deployment.cluster.elasticsearch[0].https_endpoint}"]
    username  = ec_deployment.cluster.elasticsearch_username
    password  = ec_deployment.cluster.elasticsearch_password
  }
}

resource "elasticstack_elasticsearch_security_user" "user" {
  username = "ingest_user"
  password = "mysecretpassword"
  roles    = ["editor"]
}
```

2. TF operations to execute to get the error
    1. Apply using the above definition
    2. Delete the below definitions from the code
        - `ec_deployment.cluster`
        - `data.ec_stack.latest`
        - provider `elasticstack`
        - `elasticstack_elasticsearch_security_user.user`
    3. Apply again
    4. A error occurs

3. See the error in the output

```
elasticstack_elasticsearch_security_user.user: Refreshing state... [id=xxxxxxxxxxx/ingest_user]
ec_deployment.cluster: Refreshing state... [id=xxxxxxxxxxx]
╷
│ Error: dial tcp 127.0.0.1:9200: connect: connection refused
│ 
│ 
╵
```

I can work around this issue by first removing `elasticstack_elasticsearch_security_user.user` only (and applying), then removing `ec_deployment.cluster` and applying.
Or I can also work around it by using the [deprecated `elasticserach_connection` block](https://github.com/elastic/terraform-provider-elasticstack/blob/351ba9eb9ddda280caa78250ed519a0a1830cf45/docs/resources/elasticsearch_security_system_user.md?plain=1#L44) like below.

```
resource "elasticstack_elasticsearch_security_user" "user" {
  username = "ingest_user"
  password = "mysecretpassword"

  elasticserach_connection {
    endpoints = ["${ec_deployment.cluster.elasticsearch[0].https_endpoint}"]
    username  = ec_deployment.cluster.elasticsearch_username
    password  = ec_deployment.cluster.elasticsearch_password
  }
}
```

## Expected behavior

I expect to delete `ec_deployment` and `elasticstack_elasticsearch_security_user` in one `terraform apply` after deleting these definitions from the code.

## Versions
 - OS: I used container image `hashicorp/terraform:1.3.7` https://hub.docker.com/r/hashicorp/terraform/, and Elastic Cloud
 - Terraform Version: 1.3.7
 - Provider version
    - elastic/ec: 0.5
    - elastic/elasticstack: 0.5
 - Elasticsearch Version: 8.6.0

**Comment by k-yomo** [comment]
I think this is a known issue of terraform and not a bug of this provider...!
https://github.com/hashicorp/terraform/issues/2430

You can also explicitly specify the dependency by using `depends_on` argument.
https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on

**Comment by takashi-yokoyama-visasq** [comment]
Thank you for your comment. I understood this is terraform's issue.
It doesn't work in this situation to specify `depends_on` in the `elasticstack_elasticsearch_security_user` resource.

I will close this issue because this is not a bug for this provider.
I hope this terraform's issue will be solved.
