### ISSUE TITLE
[Bug] snapshot lifecycle config "include_global_state" not working properly

### ISSUE THREAD

**Issue by v8v5v** [elastic/terraform-provider-elasticstack#267]
**Describe the bug**
During the creation of a snapshot lifecycle the config `include_global_state` is not working properly.
If it is set to `false`, then the created lifecycle policy is created without `include_global_state` option.
 

**To Reproduce**
1. TF configuration used:
```
terraform {
    elasticstack = {
      source  = "elastic/elasticstack"
      version = ">= 0.3.3"
    }
}
variable "repository_name" {}

resource "elasticstack_elasticsearch_snapshot_lifecycle" "nightly_test" {
  name = "nightly-test"

  schedule      = "0 30 0 * * ?"
  snapshot_name = "<nightly-test-{now/d}>"
  repository    = var.repository_name

  indices              = ["logs*-test-*"]
  ignore_unavailable   = true
  include_global_state = false

  expire_after = "1825d"
}
```

2. TF operations to execute to get the error:
`terraform init && terraform apply`

3. See the error in the output:
Check the result:
`
curl -XGET "http://localhost:9200/_slm/policy/nightly-test"
`
The result config does not have `include_global_stage: false` key.

**Expected behavior**
If `elasticstack_elasticsearch_snapshot_lifecycle` has key `include_global_state = false`, the result SLM should have the key `include_global_stage: false`

**Debug output**
If it would be required, I can provide a TF debug log, need to create a simple env for that, which would take some time.

**Versions (please complete the following information):**
 - OS: linux
 - Terraform Version v1.3.5
 - Provider version 0.5.0
 - Elasticsearch Version 7.17.3

**Additional context**
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/slm-api-put-policy.html
include_global_state
Defaults to true

**Comment by tobio** [comment]
Duplicates https://github.com/elastic/terraform-provider-elasticstack/issues/109

Thanks for the report @v8v5v. This has been fixed in the main branch and will go out with the next provider release.
