### ISSUE TITLE
[Bug] Logstash pipeline pipeline_metadata.version read is failing 

### ISSUE THREAD

**Issue by jassi-singh-wig** [elastic/terraform-provider-elasticstack#278]
**Describe the bug**
resource "elasticstack_elasticsearch_logstash_pipeline" fails with the below error, when the pipeline is updated from Kibana UI or an existing pipeline is imported
```
Error: pipeline_metadata.version: '' expected type 'string', got unconvertible type 'float64', value: '1'
```

**To Reproduce**
1. Create a logstash pipeline using terraform resource elasticstack_elasticsearch_logstash_pipeline
2. Open the pipeline in Kibana, click on Create & deploy
3. Re-run Step1 terraform
4. or, try importing an existing pipeline in terraform state

**Expected behavior**
No errors should be produced, existing logstash pipeline should be overwritten/imported by the terraform 

**Debug output**
Error: pipeline_metadata.version: '' expected type 'string', got unconvertible type 'float64', value: '1'
```
terraform import elasticstack_elasticsearch_logstash_pipeline.pipeline <cluster_uuid>/test-id
elasticstack_elasticsearch_logstash_pipeline.pipeline: Importing from ID "<cluster_uuid>/test-id"...
elasticstack_elasticsearch_logstash_pipeline.pipeline: Import prepared!
  Prepared elasticstack_elasticsearch_logstash_pipeline for import
elasticstack_elasticsearch_logstash_pipeline.pipeline: Refreshing state... [id=<cluster_uuid>/test-id]
╷
│ Error: pipeline_metadata.version: '' expected type 'string', got unconvertible type 'float64', value: '1'
│ 
│ 
╵
```

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS
 - Terraform Version v1.3.7
 - Provider version v0.5.0
 - Elasticsearch Version v8.6.2, v.7.17.8

**Additional context**

**Comment by aydasraf** [comment]
+1 on the issue. Any timeline for resolution? Will 0.6 with altering features come anytime soon?

**Comment by RobsonSutton** [comment]
@aydasraf - This should be fixed in the next version bump but will introduce a breaking change (just add jsonencode() around any existing config and it will work though). It seems 0.6.0 should be released at some point this month, once Alert Connector support has been added 👍
