### ISSUE TITLE
[Bug]  HEAD healthcheck failed!

### ISSUE THREAD

**Issue by LixvYang** [elastic/terraform-provider-elasticstack#279]
**Describe the bug**
Sorry for asking this question, when I want to check the index in my cluster, he bursts out such an error, it seems that I have not configured it well, but I configured it like this

```go
        cfg := elasticsearch.Config{
		APIKey:   os.Getenv("ELASTICSEARCH_API_KEY"),
		CloudID:  os.Getenv("ELASTICSEARCH_CloudID"),
		Username: os.Getenv("ELASTICSEARCH_USERNAME"),
		Password: os.Getenv("ELASTICSEARCH_PASSWORD"),
	}
	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		return nil, err
	}
```

In this case the error is like this:
```
[ error ] 1 error occurred:
        * HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.
```
When I debugged, I found that the error is actually caused by this interface
```go
/pkg/tfshim/shim.go

type Provider interface {
	Refresh(t string, s InstanceState) (InstanceState, error)
}
```
I don't know the function of this interface, how should I do it? About this interface. Or is there something wrong with my configuration? How do I need to configure resources?

**To Reproduce**
1. TF configuration used '...'
2. TF operations to execute to get the error '...' [e.g `terraform plan`,`terraform apply`, `terraform destroy`]
3. See the error in the output '...'

**Expected behavior**

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Linux]
 - Terraform Version [e.g. 1.0.0]
 - Provider version [e.g. v0.1.0]
 - Elasticsearch Version [e.g. 7.16.0]

**Additional context**

**Comment by tobio** [comment]
@LixvYang it sounds like you're interacting directly with the [go-elasticsearch](https://github.com/elastic/go-elasticsearch) client rather than the Terraform provider? 

Should we transfer this issue to that repo instead?

**Comment by Kushmaro** [comment]
Closing this one for now
