### ISSUE TITLE
[Bug] The client noticed that the server is not a supported distribution of Elasticsearch

### ISSUE THREAD

**Issue by lmilbaum** [elastic/terraform-provider-elasticstack#280]
**Describe the bug**
Creating an index on elasticsearch 7.1 running on AWS

╷
│ Error: the client noticed that the server is not a supported distribution of Elasticsearch
│ 
│   with elasticstack_elasticsearch_index.elasticsearch_index,
│   on main.tf line 219, in resource "elasticstack_elasticsearch_index" "elasticsearch_index":
│  219: resource "elasticstack_elasticsearch_index" "elasticsearch_index" {
│ 
╵

**To Reproduce**
1. TF configuration used '...'
2. TF operations to execute to get the error '...' [e.g `terraform plan`,`terraform apply`, `terraform destroy`]
3. See the error in the output '...'

**Expected behavior**

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Linux]
 - Terraform Version [e.g. 1.0.0]
 - Provider version [e.g. v0.1.0]
 - Elasticsearch Version [e.g. 7.16.0]

**Additional context**

**Comment by Kushmaro** [comment]
@lmilbaum , are you using the provider against AWS's opensearch service?

**Comment by lmilbaum** [comment]
> @lmilbaum , are you using the provider against AWS's opensearch service?

Yes. But, I've picked up elasticsearch version 7.1

**Comment by Kushmaro** [comment]
Sorry, but we do not support this provider against any of the AWS OpenSearch service versions. Thus, I'm closing this issue.
