### ISSUE TITLE
[Feature] Support Kibana Dataview

### ISSUE THREAD

**Issue by audig** [elastic/terraform-provider-elasticstack#314]
**Describe the resource you would like to have implemented.**
I would like to create dataview in kibana related to my index template configuration.

**Describe the solution you'd like**
I would like to declare dataview as terraform resources, example:
```
resource "elasticstack_kibana_dataview" "mydataview" {
  name           = "log"
  pattern = "log-*"
  timeFieldName = "@timestamp"
}
```

**Describe alternatives you've considered**
I considere using a rest api provider (provider restapi from mastercard), it works but it's not a unified way to declare all the eck stack configuration

**Comment by tobio** [comment]
Duplicates #75
