### ISSUE TITLE
QUESTION: roadmap - When will be the next release date of main branch

### ISSUE THREAD

**Issue by audig** [elastic/terraform-provider-elasticstack#318]
Hi,

There is planty of new features in the main branch, did you have an idea of the next release date?

I've take a look in the milestone, but i didn't find information

I'm interessted by all this features:

- Transform
- Kibana space
- Rules 
- ...

Thanks to all contributors for this provider, which is really usefull

**Comment by cerowain** [comment]
I was just coming in to raise the exact same question.  Looking forward to the new features being available.

**Comment by BrissouilleLB** [comment]
Same question for me, really waiting for new features. Can we have visibility about next release pls?

**Comment by mholttech** [comment]
We also would love to know. We have a very large environment with over 75 spaces and 100+ fleet policies, along with default alerting and index patterns customized for each space. The functionality being worked on, along with the unreleased completd functionality would benefit us immensely.

**Comment by audig** [comment]
I can close this issue, the new version "0.0.6" has been released.
Thanks
