### ISSUE TITLE
[Feature] Add resource for configuring Traffic filter

### ISSUE THREAD

**Issue by virtualaidev** [elastic/terraform-provider-elasticstack#319]
**Describe the resource you would like to have implemented**
This ticket is about adding a resource to configure traffic filter

**Describe the solution you'd like**
```
resource "elasticstack_traffic_filter" "custom_traffic_filter" {
	region = "eu-west-1"
	filter_type = "PrivateLinkEndpoint" # either IP filtering rule set or Private link endpoint
	name = "custom filter"
	description = ""
	source = [] # only required if filter type is IP rule set
	vpc_id = "vpce-08483d209354fa"
	default = true # will be included by default for any future deployments
}
```

This is needed requirements when you want to only allow certain source to access elastic service, and block the rest of them.

**Comment by tobio** [comment]
You'll find this resource in [terraform-provider-ec](https://github.com/elastic/terrraform-provider-ec).
