### ISSUE TITLE
[feature] support Elasticsearch indexes

### ISSUE THREAD

**Issue by paulojmdias** [elastic/terraform-provider-elasticstack#33]
Hi all 👋 

First of all, congratulations for building this project 🙌 

Do we have any plans to support managing Elasticsearch Indexes?

Thanks

**Comment by olksdr** [comment]
hey @paulojmdias, 
I'm pretty sure were are going to support indices as well. And @Kushmaro can provide more info on the roadmap here.

**Comment by Kushmaro** [comment]
Thanks for opening this @paulojmdias !
This is definitely something that we intend to support, as of now we're waiting for some feedback from our early users (such as yourself) to determine priority and importance, and this definitely resonates with things that we intend to support.

Do you mind if I ask for your general use case around our terraform provider in conjunction with an Index resource?
will you be looking to enforce specific index settings over indices using the provider? or is it for something more along the lines of CI/CD purposes?

**Comment by paulojmdias** [comment]
Hello @Kushmaro @olksdr,

Many thanks for at least hearing my request! :)

I want to manage Elasticsearch indices across multiple environments and clusters using Terraform and GitOps with [Atlantis](https://www.runatlantis.io/)

Of course, I want to abstract some settings in the index resource using a Terraform module, but this is for removing the dependency so everyone doesn't need to know what value could fill in a specific setting and avoiding copy-paste errors.

Regarding the details of what type of operations I want to cover with a Terraform resource:
* Creating Elasticsearch indices and defining all the possible options settings like number of shards, replicas, refresh interval, routing partition size, alias, and also mappings
* Ability to add a field to mapping without destroying the index
   * If someone trying to make a change of type in a current field mapping the behavior should re-create the index
* Ability to move alias between indices
   * Example: moving the alias dummy from index dummy_v1 to dummy_v2 without destroying the index
* Have a flag `force_destroy` that could manage  the ability to protect the index destroy if the value is `false`

We already use a Terraform provider, but most of these operations aren't allowed without destroying the index and Elasticsearch supports them without destroying and this has a huge impact on the automation process.

Feel free to ask more questions, I am able to help to grow this project. 🙌

**Comment by gtheodorio** [comment]
I also would love the ability to create ES indices. Currently getting around this by creating an index template, life cycle config, and adding an alias, but would be nice to just create indices and aliases.

**Comment by JoaoSerras** [comment]
+1 for this feature 🙌 
It would be lovely to have this available

**Comment by paulojmdias** [comment]
Many thanks, @olksdr 🙏 

I will test it when it merged and released

**Comment by olksdr** [comment]
New version of the provider was published, see: [v0.2.0](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.2.0)
