### ISSUE TITLE
[Feature] 0.6.0 release

### ISSUE THREAD

**Issue by thomas-parrish-axi** [elastic/terraform-provider-elasticstack#330]
**Is your feature request related to a problem? Please describe.**
Hi, I can see that all the PRs associated with [release 0.6.0](https://github.com/elastic/terraform-provider-elasticstack/milestone/3) have been completed, could I get an update on when that will be released?

**Describe the resource you would like to have implemented.**
I'd like access to the newer resource types that have been implemented in 0.6.0.

**Describe the solution you'd like**
A tagged version published to https://registry.terraform.io/ that I can use as part of standard terraform modules.

**Describe alternatives you've considered**
Referencing the main branch of this repository. However, this adds management overhead, and exposes us to potentially incomplete features and bugs.

**Additional context**
Raised as I noticed that https://github.com/elastic/terraform-provider-elasticstack/issues/46 the last issue for the 0.6.0 milestone has been resolved.

**Comment by Kushmaro** [comment]
Hi @thomas-parrish-axi 
The provider will be released soon. We can't provide exact dates, unfortunately.
the best way to test existing PRs and new functionality so long the provider isn't released, is simply by building it from source.
