### ISSUE TITLE
[Feature] Manage Synthetic Monitors

### ISSUE THREAD

**Issue by mholttech** [elastic/terraform-provider-elasticstack#335]
With the GA Release of [Synthetic Monitoring](https://www.elastic.co/guide/en/observability/8.8/whats-new.html#_synthetic_monitoring_goes_ga), I would like to see the ability to manage monitors with Terraform. We currently leverage a GitOps approach to manage all of our heartbeat configurations and would like to pivot to IaC for managing these monitors.

**Comment by ameindel** [comment]
+1

We are using Elastic Synthetics pretty heavily and we would also like to be able to create them via Terraform.

**Comment by tobio** [comment]
Closing this in favour of #610. I know this is the original but the other issue has some work attached to it. @ameindel @mholttech I don't have a timeframe to share, but we're actively working on adding support here.
