### ISSUE TITLE
Support self-signed / internal Certificate Authorities

### ISSUE THREAD

**Issue by utilitynerd** [elastic/terraform-provider-elasticstack#34]
My Elasticsearch cluster uses an internal Certificate Authority to secure all network communication.  When I try and use this provider with my cluster, I get:  Error: x509: certificate signed by unknown authority

I see the "ec" provider supports  "insecure = true", but when I try adding setting to this provider, I get:  An argument named "insecure" is not expected here.

Is there any way to use this provider with self signed / internal  certificates?

**Comment by Kushmaro** [comment]
Thanks @utilitynerd ! 

We didn't include such support in the initial version we've released but that's definitely something we'll be looking into and hopefully be able to deliver on soon.

**Comment by utilitynerd** [comment]
I've never actually tried submitting a PR request to an open source project before, but this issue was blocking my adoption of the provider so I figured I would give it go.

**Comment by olksdr** [comment]
New version of the provider was published, see: [v0.2.0](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.2.0)
