### ISSUE TITLE
[Bug]  Failed to create elasticstack_kibana_alerting_rule and elasticstack_kibana_action_connector resources with elasticstack 0.6.1

### ISSUE THREAD

**Issue by GopalaDuggina** [elastic/terraform-provider-elasticstack#354]
**Describe the bug**
Terraform Failed to create `elasticstack_kibana_alerting_rule` and `elasticstack_kibana_action_connector` resources  with elasticstack 0.6.1 and throwing `unsupported protocol scheme errors`

**Expected behavior**
Terraform should be able to create `elasticstack_kibana_alerting_rule` and `elasticstack_kibana_action_connector` resources on TF apply

**Current Behavior**
Terraform throwing an error while creating resources 

### My current configuration

**main.tf**

![image](https://github.com/elastic/terraform-provider-elasticstack/assets/62770568/ea0e094e-cae1-41dc-9d7e-235820ae815e)

**alert-rule.tf**

![image](https://github.com/elastic/terraform-provider-elasticstack/assets/62770568/a1a4b102-d189-409d-a704-3530b45d2434)

and these are the TF error messages

Plan: 1 to add, 0 to change, 0 to destroy.
elasticstack_kibana_alerting_rule.test-alert-rule: Creating...
╷
**│ Error: Post "/s/default/api/alerting/rule/": unsupported protocol scheme ""**
│ 
│   with elasticstack_kibana_alerting_rule.test-alert-rule,
│   on alert_rule.tf line 2, in resource "elasticstack_kibana_alerting_rule" "test-alert-rule":
│    2: resource "elasticstack_kibana_alerting_rule" "test-alert-rule" {

Plan: 1 to add, 0 to change, 0 to destroy.
elasticstack_kibana_action_connector.test_webhook_connector: Creating...
╷
**│ Error: unable to create connector: [Post "/s/default/api/actions/connector": unsupported protocol scheme ""]**
│ 
│   with elasticstack_kibana_action_connector.test_webhook_connector,
│   on alert_rule.tf line 24, in resource "elasticstack_kibana_action_connector" "test_webhook_connector":
│   24: resource "elasticstack_kibana_action_connector" "test_webhook_connector" {

## My Environment
Versions used:

elastic/terraform-provider-elasticstack  v0.6.1
Terraform v1.4.6

**Comment by tobio** [comment]
It doesn't look like you're configuring the Kibana endpoints in the provider. You'll need to update the provider configuration to something like:

```
provider "elasticstack" {
  elasticsearch {
    ...
  }
  kibana {
    endpoints = ["http://example.com/kibana"]
  }
}
```
