### ISSUE TITLE
[Feature] Allow for skip_destroy on elasticstack_fleet_agent_policy

### ISSUE THREAD

**Issue by andrewkroh** [elastic/terraform-provider-elasticstack#356]
Allow setting `skip_destroy` on the [elasticstack_fleet_agent_policy](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/fleet_agent_policy) resource.

Proposed description:

> skip_destroy - (Optional) Set to true if you do not wish the agent policy to be deleted at destroy time, and instead just remove the agent policy from the Terraform state.

This would be useful when your enrolled Fleet agents are not managed by Terraform. In this case Terraform does not know if it is safe to remove the policy because there may be enrolled agents that are still assigned to this policy. It is not possible, nor would be it safe, to delete an agent policy while an agent is using it.

A similar option is available for other providers' resources for similar reasons. See this [query](https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fregistry.terraform.io%2Fproviders%2F+skip_destroy&t=h_&ia=web).

**Comment by ebeahan** [comment]
PR: https://github.com/elastic/terraform-provider-elasticstack/pull/357
