### ISSUE TITLE
[Feature] Add API Key authentication to kibana

### ISSUE THREAD

**Issue by aydasraf** [elastic/terraform-provider-elasticstack#364]
Currently, Kibana section only support token-based authentication method by providing username and password as argument, however in most of the modern setups this not ideal.

Since kibana rest API natively support  key-based authentication via API keys. it is extremely important to have the support for this method in the Terrafrom Side.

Since this option already exists in the elasticsearch part of the provider, i think the fix should be rather quick as the structure of the call is pretty much the same.

What needs to be done:
- Add `api_key` as supported argument for the kibana configuration of the provider.
-  implement the underlying call to support this method

Refrences:
[1] https://www.elastic.co/guide/en/kibana/current/api.html
[2] https://www.elastic.co/guide/en/kibana/current/api-keys.html

**Comment by iamhowardtheduck** [comment]
My customer is currently experiencing this issue as well.
