### ISSUE TITLE
[Feature] ca_file for Kibana Connection

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/terraform-provider-elasticstack#368]
**Is your feature request related to a problem? Please describe.**
We use a custom CA to generate our certificates. In the elasticsearch and fleet blocks, we can provide a custom ca cert file for validating the server certificate but for Kibana, there is no such thing.

**Describe the solution you'd like**
We would like to have an option similar to `ca_file` in elasticsearch or `ca_certs` in Fleet connection.

**Describe alternatives you've considered**
Currently, we use `insecure=true` to make the connection work but this is not a good solution.

**Comment by tobio** [comment]
@jacobmw that should be fixed by https://github.com/elastic/terraform-provider-elasticstack/pull/585.
