### ISSUE TITLE
elasticsearch client not found when working on multiple ES clusters

### ISSUE THREAD

**Issue by radicaled42** [elastic/terraform-provider-elasticstack#408]
**Describe the bug**
Basically I'm trying to make changes on multiple ES cluster using Terraform
I'm using CDKTF with typescript to make my infra.

**To Reproduce** 
1. TF configuration used

I have set up a config json (where you can have 1 to N clusters):
```
{
  "elasticClusters": [
    {
      "name": "example",
      "endpoint": "XXXXXX",
      "password": "XXXXXX",
      "apiKeys": [],
      "indexTemplates": [
        {
          "name": "test-v8.5.1-",
          "pattern": "test-v8.5.1-*"
        }
      ]
    }
  ]
}
```

The idea of the code is to traverse the array of clusters and configure them.

This an example of the code using **multiple providers**:
```
config.elasticClusters?.forEach((elasticConfig) => {
  const elasticProvider = new ElasticstackProvider(
    this,
    `elasticsearch_provider_${elasticConfig.name}`,
    {
      alias: `elasticsearch_provider_${elasticConfig.name}`,
      elasticsearch: {
        endpoints: [elasticConfig.endpoint],
        username: 'elastic',
        password: elasticConfig.password,
      },
    }
  );
  
  const apisEsRole = new ElasticsearchSecurityRole(
    this,
    `elasticsearch_role_apis_${elasticConfig.name}`,
    {
      provider: elasticProvider,
      name: 'APIs',
      cluster: ['monitor'],
      indices: [
        {
          names: [
            'test-v*',
          ],
          privileges: ['create_doc', 'create_index', 'auto_configure', 'write'],
        },
      ],
    }
  );
}
```

I have also tested with **one provider**, outside the _forEach_ and using the **elasticsearchConnection** (although I believe it will be deprecated).
This way:
```
    new ElasticstackProvider(this, 'elasticsearch_provider', {});

    elasticClusters.forEach((elasticConfig) => {

      const apisEsRole = new ElasticsearchSecurityRole(
        this,
        `elasticsearch_role_apis_${elasticConfig.name}`,
        {
          elasticsearchConnection: {
            endpoints: [elasticConfig.endpoint],
            username: 'elastic',
            password: elasticConfig.password,
          },
          name: 'APIs',
          cluster: ['monitor'],
          indices: [
            {
              names: [
                'test-v*',
              ],
              privileges: ['create_doc', 'create_index', 'auto_configure', 'write'],
            },
          ],
        }
      );
    }
```

2. TF operations to execute to get the error
- Just **terraform plan** its failing with the plan

3. See the error in the output

- This is the error I'm getting from TF:
```
         ╷
         │ Error: elasticsearch client not found
         │
         │
         ╵
```

**Expected behavior**
I expect the changes to be done on all the Elastic Clusters

**Debug output**
Unable to share Debug, because it contains multiple passwords.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: [e.g. Linux]
   - Windows and Linux 
 - Terraform Version [e.g. 1.0.0]
    - Terraform v1.3.7 
 - Provider version [e.g. v0.1.0]
   - latest 
 - Elasticsearch Version [e.g. 7.16.0]
   - 8.9.0 

Note:
[this](https://github.com/elastic/terraform-provider-elasticstack/blob/94bcb7c6cb852c62c6ff96a776666f92dad7dae3/internal/clients/api_client.go#L212) is the only place in the code I found the same message

**Comment by tobio** [comment]
IIUC this is a configuration or CDKTF issue. 

Testing the provider within a basic forEach loop works as expected: 

```javascript
import { Construct } from "constructs";
import { App, TerraformStack } from "cdktf";
import { EcProvider } from "./.gen/providers/ec/provider";
import { Deployment } from "./.gen/providers/ec/deployment";
import { ElasticstackProvider } from "./.gen/providers/elasticstack/provider";
import { ElasticsearchIndex } from "./.gen/providers/elasticstack/elasticsearch-index";

class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new EcProvider(this, "ec", {
      apikey: "abc123"
    });

    const deployments = ["foo", "bar"];
    deployments.forEach((name) => {
      const deployment = new Deployment(this, `cdktf-${name}`, {
        region: "us-east-1",
        version: "8.9.0",
        name: `CDKTF-${name}`,
        deploymentTemplateId: "aws-general-purpose-v5",
        elasticsearch: {
          hot: {
            size: "1g",
            zoneCount: 1,
            autoscaling: {}
          }
        },
        kibana: {}
      });

      const esProvider = new ElasticstackProvider(this, `cloud_provider_${name}`, {
        alias: `cloud_provider_${name}`,
        elasticsearch: {
          endpoints: [deployment.elasticsearch.httpsEndpoint],
          username: deployment.elasticsearchUsername,
          password: deployment.elasticsearchPassword
        }
      });

      new ElasticsearchIndex(this, `index-${name}`, {
        provider: esProvider,
        name: `test-${name}`,
        deletionProtection: false
      });
    });
  }
}

const app = new App();
new MyStack(app, "mod");
app.synth();
```

> I have also tested with one provider, outside the forEach and using the elasticsearchConnection (although I believe it will be deprecated).

Did you get the same result outside of the loop?

**Comment by radicaled42** [comment]
Actually this was my fault. After a code check at 2am (I hate this kind of issues because you think everything should be working and keep me up) and reading multiple documentations and guides I realized that there is always one provider without alias.

If you check my code, I'm always adding an **alias**. 

```
  const elasticProvider = new ElasticstackProvider(
    this,
    `elasticsearch_provider_${elasticConfig.name}`,
    {
      alias: `elasticsearch_provider_${elasticConfig.name}`,
      elasticsearch: {
        endpoints: [elasticConfig.endpoint],
        username: 'elastic',
        password: elasticConfig.password,
      },
    }
  );
```

The [documentation](https://developer.hashicorp.com/terraform/language/providers/configuration#default-provider-configurations) doesn't explicitly mention that there needs to be a provider without alias (default). 
But it says:
> If every explicit configuration of a provider has an alias, Terraform uses the implied empty configuration as that provider's default configuration. (If the provider has any required configuration arguments, Terraform will raise an error when resources default to the empty configuration.)

In this case, there will be an empty default provider with no **elasticsearch** connection and there comes the **Error: elasticsearch client not found** error.

The fix was simple, I added the **index** to the forEach and check the index value. If the **index  === 0** then the alias is **undefined**, otherwise **elasticsearch_provider_${elasticConfig.name}**. 
This way, I always have a default provider.

```
config.elasticClusters?.forEach((elasticConfig, index) => {
  const elasticProvider = new ElasticstackProvider(
    this,
    `elasticsearch_provider_${elasticConfig.name}`,
    {
      alias: index !== 0 ? `elasticsearch_provider_${elasticConfig.name}` : undefined,
      elasticsearch: {
        endpoints: [elasticConfig.endpoint],
        username: 'elastic',
        password: elasticConfig.password,
      },
    }
  );
}
```
  
I hope this helps someone with similar problem ;) 
Thanks
