### ISSUE TITLE
[Feature] Support for Alert Connectors

### ISSUE THREAD

**Issue by RobDTech** [elastic/terraform-provider-elasticstack#46]
Having the ability to add and maintain connectors used for alerts

**Comment by RobDTech** [comment]
https://www.elastic.co/guide/en/kibana/master/actions-and-connectors-api.html
Create/Update/Delete

**Comment by acrewdson** [comment]
+1

**Comment by ericlundmark** [comment]
Is there any way to know when this feature will be developed or if it is even in progress?

**Comment by RobDTech** [comment]
Can’t wait to get this and the alerts features. It’s holding up our expansion of Elastic Cloud at the moment

**Comment by fludo** [comment]
+1
