### ISSUE TITLE
[Feature] Support for Role Mappings

### ISSUE THREAD

**Issue by RobDTech** [elastic/terraform-provider-elasticstack#47]
Having the ability to add and maintain Role Mappings for use with SAML

**Comment by RobDTech** [comment]
This provider is fantastic, it’s going to save us from the painful mess of shell scripts we currently use

**Comment by sabedevops** [comment]
+1. We have to use phillbaker/terraform-provider-elasticsearch for now, until this is implemented.

**Comment by RobDTech** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role-mapping.html

**Comment by Kushmaro** [comment]
thanks @RobDTech @sabedevops , for the great feedback. we will take this into consideration for the next version.
please feel free and welcome to open any further tickets on any additional functionality you think is helpful.

**Comment by fludo** [comment]
@Kushmaro Any clue when this will be available ?
