### ISSUE TITLE
[Bug] Terraform provider throws panic if configuration is set to empty strings

### ISSUE THREAD

**Issue by SignalRichard** [elastic/terraform-provider-elasticstack#487]
**Describe the bug**
The Terraform provider throws a panic error (`panic: interface conversion: interface {} is nil, not string`) if the attributes are set to empty strings.

**To Reproduce**
1. TF configuration used:

`main.tf`:
```hcl
terraform {
  required_version = "= 1.6.3"

  required_providers {
    elasticstack = {
      source = "elastic/elasticstack"
      version = "0.10.0"
    }
  }

  backend "local" {
  }
}

variable "elasticsearch_username" {
  type = string
  default = ""
}

variable "elasticsearch_password" {
  type = string
  default = ""
}

variable "elasticsearch_endpoint" {
  type = string
  default = ""
}

provider "elasticstack" {
  elasticsearch {
    username = var.elasticsearch_username
    password = var.elasticsearch_password
    endpoints = [var.elasticsearch_endpoint]
  }
}

data "elasticstack_elasticsearch_info" "cluster_info" {
  for_each = toset([])
}
```

`test.tfvars`:
```
elasticsearch_password = "none"
elasticsearch_username = "none"
elasticsearch_endpoint = "none"
```

2. TF operations to execute to get the error:

First run `terraform init`

Then, to get the panic error run `terraform plan` and to get a successful plan run `terraform plan -var-file="test.tfvars"`

**Expected behavior**

If attributes are not allowed to be set to empty strings this should be caught with provider validation errors instead of a panic error

**Versions (please complete the following information):**
 - OS: Windows 11
 - Terraform Version: 
 ```
Terraform v1.6.3
on windows_amd64
+ provider registry.terraform.io/elastic/elasticstack v0.10.0
```
 - Provider version: v0.10.0

**Additional context**

* Link to project: [https://github.com/SignalRichard/terraform-provider-elasticstack-issue](https://github.com/SignalRichard/terraform-provider-elasticstack-issue)
  * Failing demo build: [https://github.com/SignalRichard/terraform-provider-elasticstack-issue/actions/runs/6934016840/job/18861371353](https://github.com/SignalRichard/terraform-provider-elasticstack-issue/actions/runs/6934016840/job/18861371353)

This issue could appear when using the `elasticstack` provider in conjunction with the `ec` provider to bring up infrastructure if the infrastructure resources are feature flagged and in some cases may not be created leaving the `elasticstack` provider with an empty configuration.

**Comment by stefanfreitag** [comment]
Hi @SignalRichard,
do you experience the same when using the latest version v0.11.0?
I took the demo code you provided and no panic showed up.

```
❯ terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding elastic/elasticstack versions matching "0.11.0"...
- Installing elastic/elasticstack v0.11.0...
- Installed elastic/elasticstack v0.11.0 (signed by a HashiCorp partner, key ID 7FE579EDEC6DAA7B)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

❯ terraform plan

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

❯ terraform plan -var-file="test.tfvars"

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
Would need to check a bit more in detail what changed in the provider.

Cheers,
Stefan

**Comment by tobio** [comment]
This panic cannot be reproduced in the latest provider version.
