### ISSUE TITLE
[Bug] Kibana action connector can not be created while reusing the api_key from elasticsearch due to Unauthorized error. 

### ISSUE THREAD

**Issue by aleksandermiszkiewicz** [elastic/terraform-provider-elasticstack#489]
**Describe the bug**
I'm trying to use elasticstack provider to create Kibana alerts related resources. The API KEY is the only which I can use for this, but I'm receiving the `Unauthorized` response. 

` Error: Unauthorized: [security_exception: [security_exception] Reason: unable to authenticate user [] for REST request [/_security/_authenticate]]: unable to authenticate user [] for REST request [/_security/_authenticate]`
 
**To Reproduce**

```
terraform {
  required_providers {
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "~>0.10"
    }
  }
  required_version = ">= 1.0.0"
}

provider "elasticstack" {
  elasticsearch {
    api_key   = "base64encodedAPIKEY"
  }
  kibana {
    endpoints = ["https://test.elastic-cloud.com"]
  }
}


resource "elasticstack_kibana_action_connector" "example" {
  name = "cdc_eng_slack"
  connector_type_id = ".slack_api"
  secrets = jsonencode({
    webhookUrl = "https://hooks.slack.com/services/test"
  })
  space_id = "test"
}
```
**Expected behavior**
I'm able to use API KEY to create Kibana resources (`elasticstack_kibana_*`)

**Debug output**
```
---[ REQUEST ]---------------------------------------
POST /s/cloud-devops-core/api/actions/connector HTTP/1.1
Host: test.elastic-cloud.com
User-Agent: Go-http-client/1.1
Content-Length: 80
Authorization: ***********
Content-Type: application/json
Kbn-Xsrf: true
Accept-Encoding: gzip

{
 "connector_type_id": ".slack_api",
 "name": "cdc_eng_slack",
 "secrets": {
  "token": ""
 }
}
-----------------------------------------------------: tf_req_id=4aa21ec1-88ee-12c2-685b-c66ba0f6cf17 tf_resource_type=elasticstack_kibana_action_connector @module=elasticstack tf_mux_provider=*schema.GRPCProviderServer tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_rpc=ApplyResourceChange @caller=github.com/elastic/terraform-provider-elasticstack/internal/utils/http_log.go:39 timestamp=2023-11-22T15:21:37.785+0100
2023-11-22T15:21:38.220+0100 [DEBUG] provider.terraform-provider-elasticstack_v0.10.0: Kibana Action Connectors API Response Details:
---[ RESPONSE ]--------------------------------------
```

**Versions (please complete the following information):**
 - OS: MacOs
 - Terraform Version: 1.5.6
 - Provider version: v0.10.0
 - Elasticsearch Version: 8.4.3
 
**Additional context**
When I'm using the same API Key and I'm doing simple REST API call I'm able to create the kibana connector.

**Comment by tobio** [comment]
The provider doesn't support API key auth for Kibana resources at the moment. Supports being added in https://github.com/elastic/terraform-provider-elasticstack/pull/372. Closing this as a duplicate.
