### ISSUE TITLE
[Bug] Import of Fleet Agent Policy does not capture and populate  policy_id field

### ISSUE THREAD

**Issue by dejongm** [elastic/terraform-provider-elasticstack#496]
**Describe the bug**
When importing an existing  Fleet Agent Policy into Terraform State, it does not capture the policy_id of the policy. I believe this is causing issues with the `elasticstack_fleet_enrollment_tokens` data object, in that it collects every token for every Agent policy in the query associated with the malformed fleet agent policy resource.

This is an example of an imported fleet_agent_policy resource. **Note the missing `policy_id` field.**

```
# module.fleet_agent_policy["Default Policy"].elasticstack_fleet_agent_policy.main:
resource "elasticstack_fleet_agent_policy" "main" {
    description     = "Default agent policy"
    id              = "7254ece0-8d5c-11ee-8101-5972d5470162"
    monitor_logs    = true
    monitor_metrics = true
    name            = "Default Policy"
    namespace       = "default"
    sys_monitoring  = true
}
```

The following is an example of a fleet policy resource created by Terraform with the policy_id field intact. 
```
# module.fleet_agent_policy["AWS-EKS Pod Policy"].elasticstack_fleet_agent_policy.main:
resource "elasticstack_fleet_agent_policy" "main" {
    description     = "AWS-EKS Pod Policy"
    id              = "8c3e2370-8ec8-11ee-8101-5972d5470162"
    monitor_logs    = true
    monitor_metrics = true
    name            = "AWS-EKS Pod Policy"
    namespace       = "default"
    policy_id       = "8c3e2370-8ec8-11ee-8101-5972d5470162"
    sys_monitoring  = true
}
```

**To Reproduce**
1. terraform import module.fleet_agent_policy[\"Default\ Policy\"].elasticstack_fleet_agent_policy.main <policy_id>

**Expected behavior**
Importing the resource should collect all the relevant fields to the resource. 

**Debug output**
N/A

**Screenshots**
N/A
**Versions (please complete the following information):**
 - OS: Linux
 - Terraform Version v1.3.9
 - Provider version v.0.10.0
 - Elasticsearch Version 8.11

**Additional context**

**Comment by dejongm** [comment]
As a side note,  I just confirmed that manually adding the poilcy_id into the statefile fixes the agent policy token query.

**Comment by GeorgeGkinis** [comment]
We come against this issue also when importing policies with an import block.
While we set the policy_id in our resource, terraform plan says that the policy needs to be destroyed:

```
locals {
  agent-policies = setunion(
    fileset(path.module, "${path.module}/agent-policies/*.json"),
    fileset(path.module, "${path.module}/../../base/agent-policies/*.json")
  )
  agent-policy-json-data  = [ for f in local.agent-policies : jsondecode(file("${path.module}/${f}")) ]
}

# Resolves  {"statusCode":409,"error":"Conflict","message":"Agent Policy 'Agent-policy' already exists with name 'Agent-policy'"}
import {
  for_each = { for ap in local.agent-policy-json-data : ap.item.id => ap }
  to = elasticstack_fleet_agent_policy.agent-policies[each.key]
  id = each.value.item.id
}

resource "elasticstack_fleet_agent_policy" "agent-policies" {
  #lifecycle { create_before_destroy= true }
  for_each = { for ap in local.agent-policy-json-data : ap.item.id => ap }
  name            = each.value.item.name
  policy_id = each.value.item.name
  namespace       = each.value.item.namespace
  description     = each.value.item.description
  sys_monitoring  = true
  monitor_logs    = true
  monitor_metrics = true
  skip_destroy = false
}
```

output:
```
Terraform will perform the following actions:

  # elasticstack_fleet_agent_policy.agent-policies["Agent-policy"] must be replaced
  # (imported from "Agent-policy")
  # Warning: this will destroy the imported resource
-/+ resource "elasticstack_fleet_agent_policy" "agent-policies" {
        description     = "blah"
      ~ id              = "Agent-policy" -> (known after apply)
        monitor_logs    = true
        monitor_metrics = true
        name            = "Agent-policy"
        namespace       = "default"
      + policy_id       = "Agent-policy" # forces replacement
      + skip_destroy    = false
      + sys_monitoring  = true
    }
```

This creates the issue that policies are getting deleted, the fleet api keys also and we cannot apply because the policy cannot be deleted when we have agents enrolled.

We need the policy to be updated, not destroyed and created again.

**Comment by GeorgeGkinis** [comment]
I can also verify that manually filling in "policy_id" in my state file fixes this issue.

**Comment by GeorgeGkinis** [comment]
I was able to update Fleet policies in-place with agents enrolled. This was done by setting the policy_id field in the provider source code.

Pull request: https://github.com/elastic/terraform-provider-elasticstack/pull/645

**Comment by GeorgeGkinis** [comment]
@tobio Please take a look at my PR and let me know if it is ok.
Also I see that there is a release approximately every month.

Is it realistic to expect this issue to be fixed within 2 months?
Otherwise we need to figure out a workaround with my colleagues.

Thanks!

**Comment by GeorgeGkinis** [comment]
I suppose this can be closed?
