### ISSUE TITLE
[feature] support kibana spaces

### ISSUE THREAD

**Issue by Kushmaro** [elastic/terraform-provider-elasticstack#5]
placeholder. details tbd, will edit once we have them.

**Comment by alexfrancoeur** [comment]
+1 to support, this was recently raised during a customer call.

**Comment by Andyandpandy** [comment]
Also interested in this. +1

**Comment by slzmruepp** [comment]
We would love to see more extensive kibana support too. Trying to onboard multiple teams/projects and seggregate through spaces.
