### ISSUE TITLE
[Bug] Creation of s3 snapshot repository fails when arn is provided

### ISSUE THREAD

**Issue by tophokie** [elastic/terraform-provider-elasticstack#50]
When attempting to create a s3 repository with an associated role_arn, receive an error that the role_arn setting is unsupported. The api supports this as follows:

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshots.html

Error below:

│ Error: Unsupported argument
│ 
│   on main.tf line 76, in resource "elasticstack_elasticsearch_snapshot_repository" "elasticsearch_migration_snapshots_repository":
│   76:     role_arn 					= "${var.iam_role_arn}"
│ 
│ An argument named "role_arn" is not expected here.

**Comment by Kushmaro** [comment]
Hi @tophokie , this provider is for managing Elasticsearch only at this time. We do not currently support any Opensearch functionality.
