### ISSUE TITLE
[Bug] role mappings being created when name is changed but not replacing or removing what is replaces

### ISSUE THREAD

**Issue by SquareShark** [elastic/terraform-provider-elasticstack#501]
As the title says, Role mappings are just being created if you change the name of them, rather than the old resources being updated or removed. In the [Roles.go](https://github.com/elastic/terraform-provider-elasticstack/blob/main/internal/elasticsearch/security/role.go) inside the name block on Line 30, you have `ForceNew:    true,`. But nothing similar in the [role_mappings.go](https://github.com/elastic/terraform-provider-elasticstack/blob/main/internal/elasticsearch/security/role_mapping.go) name block.

Can we add that little line into the role_mapping.go pretty please.

**Comment by tobio** [comment]
Thanks again for taking the time to improve the provider @SquareShark!

**Comment by tobio** [comment]
> Just curious on when the next planned release is?

@SquareShark I've just released 0.11 including these changes :)
