### ISSUE TITLE
[Feature] Support for ingest pipelines

### ISSUE THREAD

**Issue by nixfloyd** [elastic/terraform-provider-elasticstack#56]
Add the ability to manage [Ingest Pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/ingest.html) definitions.

**Comment by olksdr** [comment]
Initial PR https://github.com/elastic/terraform-provider-elasticstack/pull/57 to add the resource. But there should be few followup PRs to add data_sources to manage processors as well.

**Comment by olksdr** [comment]
New version of the provider released: [v0.3.0](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.3.0)
