### ISSUE TITLE
[Feature] Managing dashboards

### ISSUE THREAD

**Issue by pravan07** [elastic/terraform-provider-elasticstack#578]
Are there existing resources to manage/create kibana dashboards?
I did not find anything specific. Any help is appreciated.

**Comment by oshmyrko** [comment]
Seem the only way to do that is to export dashboards manually and import using [elasticstack_kibana_import_saved_objects](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/kibana_import_saved_objects).
