### ISSUE TITLE
[Bug] destory elasticstack_kibana_data_view

### ISSUE THREAD

**Issue by jeangho293** [elastic/terraform-provider-elasticstack#579]
There's a bug where the existing data view is destroyed/replaced according to popular items despite setting `"override = true."`

It seems like there's an issue where destruction occurs whenever a popular field is added or removed, which might not be the intended behavior. Additionally, the problem persists even after setting `"override."`

**Screenshots**
<img width="292" alt="image" src="https://github.com/elastic/terraform-provider-elasticstack/assets/84619866/61dcdc9e-915e-4475-bd65-e99845fdcb7e">

<img width="689" alt="image" src="https://github.com/elastic/terraform-provider-elasticstack/assets/84619866/23a27178-c36a-472d-a89d-1fd6aefb7d96">

**Versions (please complete the following information):**
 - OS: MacOs
 - Terraform Version: 1.3.6 on darwin_arm64
 - Provider version: 0.11.1
 - Elasticsearch Version: 8.4

**Comment by tobio** [comment]
@jeangho293 are you able to post a set of repro steps for this?
