### ISSUE TITLE
[Bug] Mapping type missing

### ISSUE THREAD

**Issue by RobertPasRPM** [elastic/terraform-provider-elasticstack#58]
Hi, I am trying to create an index using this code:
```
resource "elasticstack_elasticsearch_index" "test-index" {
  name = "test-index"

  elasticsearch_connection {
    endpoints = [ var.elastic-uri ]
    password = var.elastic-password
    username = var.elastic-username
  }

  mappings = local.mapping

  settings {
    setting {
      name  = "index.number_of_replicas"
      value = "1"
    }
  }
}
```
When trying to create the index, this error appears:
```
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation
Failed: 1: mapping type is
missing;"}],"type":"action_request_validation_exception","reason":"Validation
Failed: 1: mapping type is missing;"},"status":400}
```
I am loading local.mapping using file function in locals.tf to retrieve string from a json file and the json file looks like this:
`{"mappings: {  "type_name" : { "properties":{ and here all the fields ..`

I am expecting this to work when I try to create the index using Kibana and with _PUT/index/_mapping works.

**Comment by olksdr** [comment]
Hey @RobertPasRPM, 

the error you see is coming from the Elasticsearch, where validation of the mapping is failing.  You might have to remove the `{"mappings:` part of the object from your file, and only use the part where the mapping is defined 

When you look at the example https://github.com/elastic/terraform-provider-elasticstack/blob/7118919599a2b21b5cd2bcfbaa3179a580aec3a9/examples/resources/elasticstack_elasticsearch_index/resource.tf#L19-L28 we expect to have an object which is defining the mappings already (like `properties`)

**Comment by RobertPasRPM** [comment]
I removed the mappings node, the same issue:
```
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation
Failed: 1: mapping type is
missing;"}],"type":"action_request_validation_exception","reason":"Validation
Failed: 1: mapping type is missing;"},"status":400}
```

**Comment by olksdr** [comment]
What version of the Elasticsearch do you use?

**Comment by RobertPasRPM** [comment]
6.8.15

**Comment by olksdr** [comment]
> 6.8.15

This provider supports ES versions starting from `7.x`, and some of the options just not compatible. This also mentioned in the [`README`](https://github.com/elastic/terraform-provider-elasticstack#getting-started)

In your case this looks like you're providing mapping with index type, which was deprecated in `7.x` and by default is not supported and will be completely removed in `8.x`.
  
Please, see the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
