### ISSUE TITLE
[Bug] Even with "override" set, data view destruction occurs.

### ISSUE THREAD

**Issue by jeangho293** [elastic/terraform-provider-elasticstack#581]
**Describe the bug**
There's a bug where the existing data view is destroyed/replaced according to popular fields despite setting "override = true."

**To Reproduce**
1. Create a data view with the "override=true" option using Terraform.
2. Add popular fields in Kibana.
3. Upon Terraform apply, destruction and addition occur.

**Expected behavior**
Wouldn't it be better to ignore changes in the "field_attrs" field when the "override" option is set to true?

**Screenshots**
<img width="292" alt="image" src="https://github.com/elastic/terraform-provider-elasticstack/assets/84619866/61dcdc9e-915e-4475-bd65-e99845fdcb7e">

<img width="689" alt="image" src="https://github.com/elastic/terraform-provider-elasticstack/assets/84619866/23a27178-c36a-472d-a89d-1fd6aefb7d96">

**Versions (please complete the following information):**
 - OS: `MacOs`
 - Terraform Version: `1.3.6 on darwin_arm64`
 - Provider version: `0.11.1`
 - Elasticsearch Version: `8.4`

**Comment by tobio** [comment]
> Wouldn't it be better to ignore changes in the "field_attrs" field when the "override" option is set to true?

Not really, from Terraforms point of view the current state has diverged from the desired state and so it's rightfully correcting things. 

You can potentially get this behaviour via setting [`ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) on the data view lifecycle, but this shouldn't be provider level functionality.

**Comment by jeangho293** [comment]
> > Wouldn't it be better to ignore changes in the "field_attrs" field when the "override" option is set to true?
> 
> Not really, from Terraforms point of view the current state has diverged from the desired state and so it's rightfully correcting things.
> 
> You can potentially get this behaviour via setting [`ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) on the data view lifecycle, but this shouldn't be provider level functionality.

oh. thank for your help.
