### ISSUE TITLE
[Bug] elasticstack_elasticsearch_security_api_key

### ISSUE THREAD

**Issue by syepes** [elastic/terraform-provider-elasticstack#594]
**Describe the bug**
looks like the elasticstack_elasticsearch_security_api_key recource is not working, event the defauklt example code does not working: https://github.com/elastic/terraform-provider-elasticstack/blob/b78c2ec78e21114ff802c5e78d02dc7e15a5341e/internal/elasticsearch/security/api_key_test.go#L76-L85)

**To Reproduce**

```
resource "elasticstack_elasticsearch_security_api_key" "this" {
  name = "test"
  role_descriptors = jsonencode({
    role_name = {
      role-a = {
        cluster = ["all"]
        indices = [{
          names                    = ["index-a*"]
          privileges               = ["read"]
          allow_restricted_indices = false
        }]
      }
    }
  })
}

```

**Expected behavior**
It should create the key with the defined permissions 

**Screenshots**
using the example: https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_security_api_key#api_key

![CleanShot 2024-03-21 at 4  19 03@2x](https://github.com/elastic/terraform-provider-elasticstack/assets/333081/5aa87d9e-04f6-44de-b89f-b70d7c7bf10a)

Works but does not take into account the settings:
![CleanShot 2024-03-21 at 4  24 54](https://github.com/elastic/terraform-provider-elasticstack/assets/333081/ad3ebba0-55f4-40bf-b675-782ea7563a46)

**Versions (please complete the following information):**
 - OS: [e.g. Linux]
 - Terraform Version [e.g. 1.7.0]
 - Provider version [e.g. v0.11.2]
 - Elasticsearch Version [e.g. 8.12.2]

**Comment by dimuon** [comment]
I was able to successfully run the following TF config on my local using a docker image of ES:
- start ES docker image - run `make docker-elasticsearch` from the provider repo root (it should expose ES on host port 9200)
- apply the following TF config
```
terraform {
  required_providers {
    elasticstack = {
      source  = "elastic/elasticstack"
    }    
  }
}

provider "elasticstack" {
  elasticsearch {
    endpoints = ["http://localhost:9200"]
    username = "elastic"
    password = "password"
  }
}

resource "elasticstack_elasticsearch_security_api_key" "test" {
  name = "test"
  
  role_descriptors = jsonencode({ 
    role-a = { 
      cluster = ["all"] 
      indices = [{ 
	names = ["index-a*"] 
	privileges = ["read"] 
	allow_restricted_indices = false 
      }] 
    } 
  })   
}
```

It could be that you faced with the issue described [here](https://discuss.elastic.co/t/create-an-api-key-using-a-client-authenticated-by-an-existing-api-key/341119).

**Comment by syepes** [comment]
@dimuon Thanks for checking this out, effectively it looks like its because I am trying to create an API using an API Key :-)

https://github.com/elastic/elasticsearch/issues/52244

It is still not clear if this is possible or not, I have tried creating a new using the roles "manage_api_key", "manage_own_api_key" an I am still getting the same error.


This is how I am using the TF:
```
resource "elasticstack_elasticsearch_security_api_key" "this" {
  name = "test"
  role_descriptors = jsonencode({
    role-a = {
      cluster = ["all"]
      indices = [{
        names                    = ["index-a*"]
        privileges               = ["read"]
        allow_restricted_indices = false
      }]
    }
  })
}


terraform {
  required_version = ">= 1.7"
  required_providers {
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "~>0.11"
    }
  }
}

provider "elasticstack" {
  elasticsearch {
    api_key   = "XXX"
    endpoints = ["https://XXXX.es.westeurope.azure.elastic-cloud.com:9243"]
  }
}
```
