### ISSUE TITLE
[Feature] Resource to allow creation of Index stream

### ISSUE THREAD

**Issue by bulwant** [elastic/terraform-provider-elasticstack#61]
**Is your feature request related to a problem? Please describe.**

Currently there is a elasticstack_elasticsearch_index, but none to create index streams, there is a resource to build index templates for streams, but nothing to trigger the creation of a stream. 

Similar to the following api

https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices-create-data-stream.html

**Describe the resource you would like to have implemented.**

similar to the current create streams api
(https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices-create-data-stream.html)

**Comment by olksdr** [comment]
This feature already merged and will be released in the new version, see #45
