### ISSUE TITLE
Manage saved objects 

### ISSUE THREAD

**Issue by RobDTech** [elastic/terraform-provider-elasticstack#62]
Would it be feasible to manage saved objects from Terraform? 

I'm not sure if this would be a single feature request or multiple depending on the type. The ones we are very keen on are connector, index-pattern, tags, lens and dashboard.

Thanks for the features so far, this is helping us a lot!

**Comment by nicholas-r-king** [comment]
+1 for dashboard

**Comment by eloo** [comment]
are there any plans here to get this done? 
as a paying customer its a bit sad that we are not able to properly manage saved objects...

**Comment by tobio** [comment]
We're working on adding support for Kibana resources right now and will be working through the different resources in the coming releases.

**Comment by eloo** [comment]
sounds good 👍 
thanks for the update

**Comment by timgoud** [comment]
+1

**Comment by dlaczeg** [comment]
+1

**Comment by tcase44** [comment]
+1,
any updates @tobio?

**Comment by anontrex** [comment]
+1, 
any updates @tobio?

**Comment by tobio** [comment]
Not explicitly on this issue. There's been a preference for supporting resources with richer API support, for instance alert [connectors](https://www.elastic.co/guide/en/kibana/current/create-connector-api.html#create-connector-api-request-body) vs the generic import/export flow we'd require here. 

That said, the priorities are largely driven by customer demand. This one's on the roadmap but hasn't been assigned to a milestone as yet.

**Comment by mikecalizo** [comment]
@Kushmaro Can you please provide an update on this ER?

**Comment by nicholas-r-king** [comment]
@tobio we are an enterprise customer, any idea on the roadmap for getting data-views added to the provider? Should be a relatively flushed out API and relatively straight forward add.

**Comment by mholttech** [comment]
+1 from another fellow enterprise customer

**Comment by Kushmaro** [comment]
@nicholas-r-king the roadmap is clearly displayed in the project as milestones - 
https://github.com/elastic/terraform-provider-elasticstack/milestone/5

we aim to try adding data-views in the next milestone.

Managing saved objects is currently not planned as of yet, we'll see what can be done.

**Comment by jLemmings** [comment]
Also a enterprise customer and we would like to migrate to the terraform provider to replace our custom made scripts.

**Comment by drewdaemon** [comment]
Reading this request as "manage Kibana content," I would expect the new [content management APIs](https://github.com/elastic/kibana/issues/157043) to make this easier.

**Comment by Kushmaro** [comment]
@drewdaemon care to add some support for this to kibana-go-sdk? ;)

**Comment by Kushmaro** [comment]
@RobDTech the latest version 0.11.0, allows for import of saved objects

**Comment by RobDTech** [comment]
Thanks :)
