### ISSUE TITLE
[Feature] Support adding images for spaces

### ISSUE THREAD

**Issue by tehbooom** [elastic/terraform-provider-elasticstack#659]
**Is your feature request related to a problem? Please describe.**
Currently the provider can only change the color of spaces. Would like an option to upload images for spaces.

The [kibana spaces api](https://www.elastic.co/guide/en/kibana/current/spaces-api-post.html) supports adding an image with  `imageUrl`

**Describe the resource you would like to have implemented.**
Add an optional field for image url like we do with `color` in the `elasticstack_kibana_space` resource.

**Describe the solution you'd like**
As of now the [go-kibana-rest package](https://github.com/disaster37/go-kibana-rest/blob/0b9a8c5ca23609d6ae0498e115ad988bf6fa9e6b/kbapi/api.kibana_spaces.go#L17) does not support an option for the `imageUrl`. Once the package has this option or we find another way to add that as an option, we would then be able to add an optional field for imageUrl. If imageUrl is specified color cannot be specified.

**Describe alternatives you've considered**
[go-kibana-rest](https://github.com/disaster37/go-kibana-rest) does not seem to be up to date or current with kibana features. I suggest forking this repo, commiting to this repo, or using `net/http` package to interact with the kibana API since Elastic does not have an SDK for kibana.

**Comment by tobio** [comment]
If you were looking to add this yourself, we're already using a [local fork](https://github.com/elastic/terraform-provider-elasticstack/tree/main/libs/go-kibana-rest) of `go-kibana-rest` since it appears to be abandoned by the maintainer.
