### ISSUE TITLE
Kibana breaking change: Remove Deprecated Kibana Saved Object APIs

### ISSUE THREAD

**Issue by TinaHeiligers** [elastic/terraform-provider-elasticstack#665]
Most of the Kibana Saved Objects HTTP APIs were deprecated in 8.7 (released Mar 30, 2023) and the deprecation period will run out by v9. Kibana Core plans to remove the deprecated APIs in v9 (except `_import`, `_export`, and `_resolveImportErrors`, which are public). 

The APIs listed below need to be removed and all current and future use of the Saved Objects APIs will be restricted to the public APIs.

- GET /api/saved_objects/<type>/<id>: [https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go#L71-L79](https://www.google.com/url?q=https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go%23L71-L79&sa=D&source=docs&ust=1718401180098189&usg=AOvVaw1vDOddnI59bkzT06F03N_X)
- GET /api/saved_objects/_find: [https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go#L151-L159](https://www.google.com/url?q=https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go%23L151-L159&sa=D&source=docs&ust=1718401180098288&usg=AOvVaw3wxBC7SIAXAgkHfIHfC0sr)
- POST /api/saved_objects/<type>/<id>: [https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go#L199-L211](https://www.google.com/url?q=https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go%23L199-L211&sa=D&source=docs&ust=1718401180098342&usg=AOvVaw1RNHq4Xt_6TjFRA5jHsphL)
- PUT /api/saved_objects/<type>/<id>: [https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go#L248-L260](https://www.google.com/url?q=https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go%23L248-L260&sa=D&source=docs&ust=1718401180098407&usg=AOvVaw1QBosXzfzynA38nAcbpGJG)
- DELETE /api/saved_objects/<type>/<id>: [https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go#L293-L301](https://www.google.com/url?q=https://github.com/elastic/terraform-provider-elasticstack/blob/main/libs/go-kibana-rest/kbapi/api.kibana_save_object.go%23L293-L301&sa=D&source=docs&ust=1718401180098477&usg=AOvVaw28etSG4RiqX_6yWTgHmbc-)

**Comment by tobio** [comment]
Duplicate of https://github.com/elastic/terraform-provider-elasticstack/issues/637

**Comment by TinaHeiligers** [comment]
I'd already discussed this with the team! Thanks @tobio

**Comment by TinaHeiligers** [comment]
I followed the trail and came to the same conclusion as https://github.com/elastic/terraform-provider-elasticstack/issues/659#issuecomment-2163933288. The underlying `kibana client` isn't maintained anymore. We could either update that ourselves or restrict the changes to this repo.

**Comment by TinaHeiligers** [comment]
closing as superseded by https://github.com/elastic/terraform-provider-elasticstack/issues/637
