### ISSUE TITLE
[Feature] Add functionality to create private location

### ISSUE THREAD

**Issue by ckauf** [elastic/terraform-provider-elasticstack#675]
**Is your feature request related to a problem? Please describe.**
Part of setting up the Elastic Stack is also starting a Elastic Agent docker image used for synthetic monitoring. While it is possible to add the Agent policy it is not possible to create the Private Location via Terraform.

**Describe the resource you would like to have implemented.**
[Create Private Location API](https://www.elastic.co/guide/en/kibana/current/create-private-location-api.html) 

**Describe the solution you'd like**
Be able to use the Create Private Location API via the Elasticstack Terraform provider

**Describe alternatives you've considered**
Direct use of the API is possible, either direct or via Ansible, etc, however it is a break in the configuration flow and doesn't allow state management.

**Comment by biscout42** [comment]
IIUC it is synthetics related, so I might implement it as part of https://github.com/elastic/terraform-provider-elasticstack/issues/610

**Comment by biscout42** [comment]
Should be done: https://registry.terraform.io/providers/elastic/elasticstack/0.11.6/docs/resources/kibana_synthetics_private_location

Feel free to let me know if you face any issues. There are some kibana limitation, which might affect private location usage.

**Comment by tobio** [comment]
@biscout42 can this one be closed?

**Comment by biscout42** [comment]
IMHO yes, we support private locations now.
