### ISSUE TITLE
[Feature] Add the ability to set a default data view

### ISSUE THREAD

**Issue by DBolge** [elastic/terraform-provider-elasticstack#681]
**Is your feature request related to a problem? Please describe.**
When setting multiple data views there is no way to specify a default.   

**Describe the resource you would like to have implemented.**
In elasticstack_kibana_data_view within the data_view an optional default could be set something like:

```
data_view = {
  name            = "logs-*"
  title           = "logs-*"
  time_field_name = "@timestamp"
  namespaces      = ["backend"]
  default         = true
}
```

**Describe the solution you'd like**
A default data view can be specified, this is most beneficial when multiple data views are being set.

**Describe alternatives you've considered**
The only alternative is to set a default using the [API](https://www.elastic.co/guide/en/kibana/current/data-views-api-default-set.html). This currently works as it does not impact the state. It would be much more elegant if this could be done in Terraform though.

**Additional context**
n/a

**Comment by tobio** [comment]
Duplicates https://github.com/elastic/terraform-provider-elasticstack/issues/603
