### ISSUE TITLE
[Feature]Need API key to authenticate from terraform to Elasticstack

### ISSUE THREAD

**Issue by sidharthvijayakumar** [elastic/terraform-provider-elasticstack#71]
Hey,

Need API key as an authentication mechanism instead of username and password. 

https://registry.terraform.io/providers/elastic/elasticstack/latest/docs

Currently, we are using username and password to authenticate with Elasticstack but as state files will have these details is there any secured way to authenticate with elasticstack/Kibana ?

**Comment by Kushmaro** [comment]
@sidharthvijayakumar , you can actually authenticate using environment variables, if you don't want them to be stored in the state file.

**Comment by ivan-penchev** [comment]
https://github.com/elastic/terraform-provider-elasticstack/pull/130 solves this.
