### ISSUE TITLE
[Feature] Add Support for Creation of a Private Location Resource

### ISSUE THREAD

**Issue by ameindel** [elastic/terraform-provider-elasticstack#711]
**Is your feature request related to a problem? Please describe.**
The company I work for is doing contract work for a government agency. They have strict rules about how things get deployed/created on their isolated .gov environments. One of the rules is 'things have to be in Terraform'.

**Describe the resource you would like to have implemented.**
Private Locations.

**Describe the solution you'd like**
Expanding the provider functionality to include being able to create Private Locations would be an ideal solution for what we're working on.

**Describe alternatives you've considered**
We've considered using a cli-based curl call to the POST api which would create the Private Location, but that is not the preferred way of handling that.

**Additional context**
None

**Comment by tobio** [comment]
@ameindel I believe https://github.com/elastic/terraform-provider-elasticstack/pull/696 adds this functionality? If so, this will be added in the next release which should be out within the next week.

**Comment by ameindel** [comment]
@tobio That's great news! I'll keep an eye out for the release. Thank you!
