### ISSUE TITLE
[Feature] Add the ability to add data views (ex index pattern)

### ISSUE THREAD

**Issue by CondormanFr** [elastic/terraform-provider-elasticstack#75]
When setting up a new instance, needed to create data views (ex index pattern)

https://www.elastic.co/guide/en/kibana/current/data-views-api.html

**Comment by audig** [comment]
this can be very usefull, an exemple of the resource declaration that can be implemented  
```
resource "elasticstack_kibana_dataview" "mydataview" {
  name           = "log"
  pattern = "log-*"
  timeFieldName = "@timestamp"
}
```

**Comment by SHolzhauer** [comment]
This is something we would like to have as well, however if this is implemented we would need the ability to configure the dataview(s) to be shared across all spaces, specifically in 1 or shared across multiple.

**Comment by nicholas-r-king** [comment]
This would be very useful for us. (Enterprise customer on ECK)

**Comment by mholttech** [comment]
As an Enterprise customer I am also looking for this

**Comment by nicholas-r-king** [comment]
Any update on this? I see it was added to the 0.8 milestone but the project is now on 0.10.

**Comment by Blefish** [comment]
My poor man's workaround to this (and dashboards)

The form data is an index-pattern, exported via Kibana's saved objects UI. Would love a native resource though!

```
resource "terraform_data" "object" {
  triggers_replace = filesha1(var.object_path)
  provisioner "local-exec" {
    command = join(" ", [
      "curl --fail -X POST --insecure",
      "--user '${var.kibana_user}:${var.kibana_password}'",
      "--header 'kbn-xsrf: true'",
      "--form file=@${var.object_path}",
      "${var.kibana_url}/api/saved_objects/_import?overwrite=true",
    ])
  }
}
```

**Comment by bartoszcisek** [comment]
[Elastic query alerting rule](https://www.elastic.co/guide/en/kibana/8.10/rule-type-es-query.html) definition require dataView ID as an argument. Without data source for `dataView` we need to hardocde UUID. 

Having dataView resource or at least dataView data source be super helpful.
