### ISSUE TITLE
[Bug] elasticstack_kibana_alerting_rule interval doesn't accept days

### ISSUE THREAD

**Issue by reakaleek** [elastic/terraform-provider-elasticstack#770]
**Describe the bug**
Using days in the `elasticstack_kibana_alerting_rule` `interval` option leads to an error.

**To Reproduce**

I imported an existing Kibana alert rule where the check interval is  7 days using `terraform import`

When run `terraform plan`

I get an expected diff with:

```
...
# elasticstack_kibana_alerting_rule.test-reporter will be updated in-place
  ~ resource "elasticstack_kibana_alerting_rule" "test-reporter" {
        id                    = "default/b6679cfe-e09a-4114-82ba-f1684563ee4a"
      ~ interval              = "7d" -> "1h"
...
```

But when I change the `interval` to `"7d"` in the tf file, I get the following error.

```
╷
│ Error: "interval" contains an invalid duration: time: unknown unit "d" in duration "7d"
│ 
│   with elasticstack_kibana_alerting_rule.test-reporter,
│   on 02-kibana-alert-rules.tf line 55, in resource "elasticstack_kibana_alerting_rule" "test-reporter":
│   55:   interval     = "7d"
│ 
╵
```

**Expected behavior**
I should be able to plan or apply with the interval `"7d"`

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations. **Please ensure you redact any base64 encoded credentials from your output**. 
eg
```
[DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Authorization: Basic xxxxx==
```

**Screenshots**

**Versions (please complete the following information):**
 - OS: macos 14.6.1
 - Terraform Version: v1.9.3
 - Provider version 0.11.6
 - Elasticsearch Version 8.15.1

**Additional context**

**Comment by tobio** [comment]
Related to https://github.com/elastic/terraform-provider-elasticstack/issues/829
