### ISSUE TITLE
[Bug] - can't create data streams in serverless projects

### ISSUE THREAD

**Issue by Kushmaro** [elastic/terraform-provider-elasticstack#818]
** background ** 
In serverless projects ILM policies are removed in favor of data streams.
In our terraform examples, to create a data stream, we require you to create an ILM policy (and that's our [docs example](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_data_stream)) 

** problem ** 
Since our data stream resource implements most properties as "computed' i.e read only - one can not create a data stream currently on a serverless project, using the elasticstack provider. 

** likely the solution ** 
enable the properties required to create a data stream via the API as not read-only and allow user input to the data stream resource 

![Image](https://github.com/user-attachments/assets/979a3bf6-9d3a-4bad-ba3e-f995dfccd79a)

**Comment by tobio** [comment]
@Kushmaro IIUC this can be closed out with support for DS lifecycles added in https://github.com/elastic/terraform-provider-elasticstack/issues/838. Just checking there wasn't something more that you were after here?

**Comment by Kushmaro** [comment]
thanks @tobio , closed and also tested myself to be working!
