### ISSUE TITLE
Question: How does this repo relate to the older `ec` provider?

### ISSUE THREAD

**Issue by Josh-a-e** [elastic/terraform-provider-elasticstack#83]
It looks like this supersedes this: https://github.com/elastic/terraform-provider-ec

Is there any advice on moving from one to the other?

**Comment by Kushmaro** [comment]
@Josh-a-e this provider is for the elastic stack. It doesn't supersede the "ec" provider which is for Elastic Cloud.
They actually work together to complete each other's function - 
the "ec" provider manages Elastic Cloud deployments (Spins up the stack) and this provider can configure the stack itself.

The documentation depicts how the two providers [can be used together](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/guides/elasticstack-and-cloud)
