### ISSUE TITLE
[Bug] Any changes to elasticstack_fleet_agent_policy require replacment

### ISSUE THREAD

**Issue by mag-mkorn** [elastic/terraform-provider-elasticstack#839]
**Describe the bug**
Any changes to a elasticstack_fleet_agent_policy resource trigger a replacement of the policy instead of updating in-place.

**To Reproduce**
Create elasticstack_fleet_agent_policy resource.

Update any value, we tested so far:

- sys_monitoring
- data_output_id
- monitoring_output_id

**Expected behavior**
Update the resource in-place.

**Debug output**

```
  # elasticstack_fleet_agent_policy.<redacted> must be replaced
-/+ resource "elasticstack_fleet_agent_policy" "<redacted>" {
      ~ id                   = "<redacted>" -> (known after apply)
        name                 = "<redacted>"
      ~ policy_id            = "<redacted>" -> (known after apply) # forces replacement
      ~ sys_monitoring       = true -> false # forces replacement
        # (6 unchanged attributes hidden)
    }
```

**Screenshots**

**Versions (please complete the following information):**

 - Terraform Version tag "latest" on GHA hashicorp/setup-terraform@v2
 - Provider version 0.11.8
 - Elasticsearch Version 18.5.2

**Comment by daemitus** [comment]
sys_monitoring should trigger replacement, its a POST only query param.
policy_id can't be changed either. 

Could not verify either out the output_ids fields.

```
# elasticstack_fleet_agent_policy.test will be updated in-place
  ~ resource "elasticstack_fleet_agent_policy" "test" {
      ~ data_output_id       = "0cd149cd-dd58-4d2b-bd00-d5b0fab95552" -> "f98c0dad-43c3-4756-a186-5c27a1ae3fa2"
      ~ id                   = "sample_id" -> (known after apply)
      ~ monitoring_output_id = "0cd149cd-dd58-4d2b-bd00-d5b0fab95552" -> "f98c0dad-43c3-4756-a186-5c27a1ae3fa2"
        name                 = "sample"
        # (7 unchanged attributes hidden)
    }
```

**Comment by tobio** [comment]
@mag-mkorn are you able to provide a config which reproduces this where there are no changes required to either `policy_id` or `sys_monitoring` since they both correctly require replacement.

**Comment by mag-mkorn** [comment]
> [@mag-mkorn](https://github.com/mag-mkorn) are you able to provide a config which reproduces this where there are no changes required to either `policy_id` or `sys_monitoring` since they both correctly require replacement.

In the provided example I did not manually provide a new id, but changing the outputs triggered a replacement.

Commit diff:
```
@@ -10,8 +6,8 @@ resource "elasticstack_fleet_agent_policy" "global_aws" {
   monitor_logs    = true
   monitor_metrics = true
 
-  data_output_id       = local.elasticstack_fleet_output_workaround_id
-  monitoring_output_id = local.elasticstack_fleet_output_workaround_id
+  data_output_id       = elasticstack_fleet_output.cribl.output_id
+  monitoring_output_id = elasticstack_fleet_output.cribl.output_id
 
   fleet_server_host_id = elasticstack_fleet_server_host.privatelink_fleet_server.host_id
 }
```

```
Terraform will perform the following actions:

  # elasticstack_fleet_agent_policy.global_aws must be replaced
-/+ resource "elasticstack_fleet_agent_policy" "global_aws" {
      ~ data_output_id       = "1c5690b7-0213-4725-90f2-7159ac877801" -> "14bde4fa-336d-43a8-b3d4-b3fc7254cd47"
      ~ id                   = "0563f8f2-90bf-400d-a631-1cad1754c5f8" -> (known after apply)
      ~ monitoring_output_id = "1c5690b7-0213-4725-90f2-7159ac877801" -> "14bde4fa-336d-43a8-b3d4-b3fc7254cd47"
        name                 = "Global AWS Agents Policy"
      ~ policy_id            = "0563f8f2-90bf-400d-a631-1cad1754c5f8" -> (known after apply) # forces replacement
        # (6 unchanged attributes hidden)
    }
```

**Comment by tobio** [comment]
Thanks @mag-mkorn, we've merged a fix for this which will be available in the next release, though there's no timeframe for that right now.
