### ISSUE TITLE
Make provider package importable

### ISSUE THREAD

**Issue by vinay-kosaraju** [elastic/terraform-provider-elasticstack#84]
**Is your feature request related to a problem? Please describe.**
I am taking a stab at getting a Pulumi provider built for this terraform provider using [pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate). For this to work, `provider` package needs to be importable.

Are there any plans for getting a Pulumi provider for this already? 

**Describe the solution you'd like**
Project layout similar to that of [terraform-provider-ec](https://github.com/elastic/terraform-provider-ec), to get a Pulumi provider built out of this provider.

**Comment by Kushmaro** [comment]
We don't have any direct plans as of yet of creating a Pulumi provider
however, we can consider the above request, for it to be easier to generate (/cc @olksdr )
