### ISSUE TITLE
[Feature] Add road map

### ISSUE THREAD

**Issue by marekduciuc** [elastic/terraform-provider-elasticstack#85]
**Is your feature request related to a problem? Please describe.**
The [readme.md](https://github.com/elastic/terraform-provider-elasticstack/blob/main/README.md) does not provide much information on what is the scope of this project. What are planned capabilities?  (CRUD on  indices, CRUD on index templates etc..) 
Some of these are apparent from already existing feature requests but not everything is.

**Describe the solution you'd like**
Add a more clear description of what is the plan with its project, what are planned capabilities? 

**Describe alternatives you've considered**
NONE

**Additional context**
We are designing new microservice architecture and one of the issues we want to tackle is managing our indices. We can create a new microservice for that but we can also wait if this provider will give us such ability. It will fit nicely into our company DevOps process as we use terraform a lot.

**Comment by Kushmaro** [comment]
@marekduciuc the provider already supports managing indices in its latest version ([docs](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_index))

regardless, the scope of the project is anything that sits within the API realm of the Elastic Stack. 
This means:
- Elasticsearch
- Kibana
- Fleet Server
- Enterprise Search
- APM

For Ex.
We can make this statement better in the doc, but I'll be closing this issue for now unless you have any additional queries here.
