### ISSUE TITLE
[Bug] elasticstack_kibana_alerting_rule without elasticsearch configuration

### ISSUE THREAD

**Issue by fabienduval** [elastic/terraform-provider-elasticstack#865]
**Describe the bug**
elasticstack_kibana_alerting_rule without an elasticsearch configuration, usage became impossible.

**To Reproduce**
1. Configure the provider with only a kibana configuration, no elasticsearch
`
provider "elasticstack" {
  kibana {}
}
`
2. Use a version between 0.11.7 and 0.11.9 of the provider
3. Declare a kibana alerting rule - elasticstack_kibana_alerting_rule
4. terraform init, terraform plan => there are no issue here
5. terraform apply fails, with the following error
`
Error: elasticsearch client not found
`
7. Downgrade the provider to version 0.11.6
8. terraform init, terraform apply
9. The alert is succesfully configured.

**Expected behavior**
It should work the same way as with the version 0.11.6.

**Versions (please complete the following information):**
 - OS: Linux
 - Terraform Version 1.9.6
 - Provider version 0.11.7
 - Elasticsearch Version 8.15.0

**Comment by tobio** [comment]
Thanks for reporting this @fabienduval, it'll be fixed up in the next release.
