### ISSUE TITLE
[Bug] Data source for security roles is unusable due to 'Invalid address to set: []string{"description"}'

### ISSUE THREAD

**Issue by sym-stiller** [elastic/terraform-provider-elasticstack#880]
**Describe the bug**
The data source `elasticstack_elasticsearch_security_role` seems to be unusable since provider version 0.11.9. Each plan will fail with the following message when one such data source is present:
`Error: Invalid address to set: []string{"description"}`

It looks like this error is related to https://github.com/elastic/terraform-provider-elasticstack/pull/824 , which introduced the description field to the security_role resource, but not to its data source.

**To Reproduce**
1. Have at least one `elasticstack_elasticsearch_security_role` data source in your TF plan with a provider version >= 0.11.9
2. When running the plan, you should get the error message

**Expected behavior**
I would have expected the data source to behave like it did before version 0.11.9.

**Screenshots**
![Image](https://github.com/user-attachments/assets/6f8ec95f-47e2-4197-a006-bdea9b9bd09e)
![Image](https://github.com/user-attachments/assets/bd70dfce-bf90-4180-b023-5e4d2b37e599)
The error message does not change regardless of the role name in use.

**Versions:**
 - OS: MacOS Sonoma 14.5
 - Terraform Version: 1.9.1
 - Provider version: coming from 0.11.8, trying to upgrade to 0.11.11
 - Elasticsearch Version: 8.15.2

**Comment by tobio** [comment]
Thanks @sym-stiller, this will be fixed in the next release.
