### ISSUE TITLE
[Bug] `elasticstack_kibana_synthetics_monitor` creation results in an error when applied against a serverless project

### ISSUE THREAD

**Issue by acrewdson** [elastic/terraform-provider-elasticstack#883]
**Describe the bug**

If you create a fresh serverless project and then attempt to create a synthetics monitor (use [this example](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/kibana_synthetics_monitor#example-usage) verbatim), your `terraform apply` will return an error (even though the monitor creation will have actually succeeded):

```
│ Error: Failed to create Kibana monitor `foobar1`, namespace default
│
│   with elasticstack_kibana_synthetics_monitor.my_monitor123,
│   on monitors.tf line 1, in resource "elasticstack_kibana_synthetics_monitor" "my_monitor123":
│    1: resource "elasticstack_kibana_synthetics_monitor" "my_monitor123" {
│
│ json: cannot unmarshal string into Go struct field SyntheticsMonitor.locations of type kbapi.MonitorLocationConfig
```

I think this is because serverless Kibana is currently returning `locations` in this shape:
```
 "locations": [
  "us_west"
 ],
```

Whereas hosted Elastic Cloud (8.15.3) returns the expected shape (and the `apply` succeeds):
```
 "locations": [
  {
   "id": "us-west1-a",
   "label": "North America - US West",
   "geo": {
    "lat": 44,
    "lon": -120.5
   },
   "isServiceManaged": true
  }
 ],
```

I assume this bug may be related to:
* https://github.com/elastic/terraform-provider-elasticstack/pull/823
* https://github.com/elastic/kibana/issues/194901
* https://github.com/elastic/kibana/pull/195295

I would like to be able to use the Terraform provider to create `elasticstack_kibana_synthetics_monitor`s in serverless projects, but right now this is not possible.

cc @biscout42 @shahzad31

**Comment by acrewdson** [comment]
FYI this also appears to be broken in 8.16.0.

**Comment by acrewdson** [comment]
It sounds like the breaking Kibana API changes will now be reverted, so I'll close this issue.

**Comment by jasonrhodes** [comment]
Revert PR is merged: https://github.com/elastic/kibana/pull/198511

Thanks for the feedback, folks.
