### ISSUE TITLE
[Bug] Terraform wants to replace a data view when field_attrs are added outside state

### ISSUE THREAD

**Issue by Alfaxomo** [elastic/terraform-provider-elasticstack#955]
**Describe the bug**
Terraform wants to replace a data view when removing field_attrs that were added to a data view in Kibana and outside terraform state. This causes the data view to be replaced with a new UUID which breaks saved object relationships to the data view. This occurs with & without the override parameter in place. We have temporarily introduced an ignore_changes to the field_attrs after which terraform only wants to remove a runtime_field_map.user_agent script that was also added in Kibana outside Terraform state.

**To Reproduce**
Terraform plan replacement output:

```
  # elasticstack_kibana_data_view.standalone_data_views["*_app-v3_*"] must be replaced
-/+ resource "elasticstack_kibana_data_view" "standalone_data_views" {
      ~ data_view = {
          - field_attrs       = {
              - "user_agent.app_build" = {} # forces replacement,
              - "user_agent.app_name" = {} # forces replacement,
              - "user_agent.app_version" = {} # forces replacement,
            } -> null
          ~ id                = "7d570900-2e0a-11ed-88c3-0d6d201d3230" -> (known after apply)
```

Terraform plan with ignore_changes update only output:

```
# elasticstack_kibana_data_view.standalone_data_views["*_app-v3_*"] will be updated in-place
  ~ resource "elasticstack_kibana_data_view" "standalone_data_views" {
      ~ data_view = {
            id                = "7d570900-2e0a-11ed-88c3-0d6d201d3230"
            name              = "*_app-v3_*"
          - runtime_field_map = {
              - "user_agent" = {
                  - script_source = <<-EOT
                    ... [ script_content ] ...
                  - type          = "composite" -> null
                },
            }
            # (4 unchanged attributes hidden)
        }
        id        = "default/7d570900-2e0a-11ed-88c3-0d6d201d3230"
        # (2 unchanged attributes hidden)
    }
```

**Expected behavior**
It removes the field_attrs (applies an update action) as it does with the runtime_field_map.user_agent.script_source but does not replace (delete/create) the data view.

**Debug output**
Please advise if debug is required.

**Screenshots**

**Versions (please complete the following information):**
 - OS: WSL
 - Terraform Version v1.3.7
 - Provider version v0.11.11
 - Elasticsearch Version v8.13.2

**Additional context**

**Comment by tobio** [comment]
The Kibana API only allows `field_attrs` to be supplied during creation time, hence changes to those fields are forcing recreation. You could set the ID of the data view via the [`data_view.id` attribute](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/kibana_data_view#id-2) which should provide a stable ID for other saved objects to reference. 

Otherwise, it may be worthwhile opening an issue in [elastic/kibana](https://github.com/elastic/kibana/issues) to make `field_attrs` updatable.
