### ISSUE TITLE
Terraform does not import Index Lifecycle Policy name when importing the resource

### ISSUE THREAD

**Issue by blukeguy** [elastic/terraform-provider-elasticstack#97]
When importing an existing "elasticstack_elasticsearch_index_lifecycle" resource, Terraform does not import the name field of the existing policy, which then forces a replacement of the current resource since the name field is required for that resource. The larger issue with this is that ILM Policies that are already in use by existing indices cannot be deleted since they are in use, therefore you cannot successfully manage the ILM policy with Terraform unless you first delete/detach the existing indices, then delete and recreate the policy with Terraform, and finally reingest/reattach the indices. 

For example:

```
resource "elasticstack_elasticsearch_index_lifecycle.auditbeat must be replaced"
+ name = "auditbeat" # forces replacement


Unable to delete ILM policy.

Failed with: {"error":{"root_cause":[{"type":"illegal_argument"exception","reason":"Cannot delete policy [auditbeat] It is in use by one or more indices..."}

**Comment by olksdr** [comment]
@blukeguy  what the version of the provider do you have? 
The [new version of the provider](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.3.3) was released few days ago where exactly this bug should haven been fixed.

**Comment by blukeguy** [comment]
Believe we have the version before, will download the new version. Thank you.
